export type CostTier = "$" | "$$" | "$$$";

export const COSTS: Record<string, CostTier> = {
  // ── Italian ──────────────────────────────────────────────────────────────
  "Pasta Carbonara":            "$$",
  "Pasta all'Amatriciana":      "$$",
  "Saffron Risotto":            "$$",
  "Pollo alla Cacciatore":      "$$",
  "Pizza Margherita":           "$",
  "Focaccia":                   "$",
  "Saltimbocca":                "$$",
  "Ribollita":                  "$",
  "Tiramisu":                   "$$",
  "Potato Gnocchi":             "$",
  "Panzanella":                 "$",
  "Pasta e Fagioli":            "$",
  "Bistecca alla Fiorentina":   "$$$",
  "Arancini":                   "$",
  "Osso Buco":                  "$$$",

  // ── Moroccan ─────────────────────────────────────────────────────────────
  "Chicken Tagine":                    "$$",
  "Lamb Tagine with Prunes":           "$$$",
  "Harira":                            "$",
  "Kefta Tagine":                      "$",
  "Zaalouk":                           "$",
  "Chermoula Fish":                    "$$",
  "Couscous with Seven Vegetables":    "$$",
  "Taktouka":                          "$",
  "Moroccan Carrot Salad":             "$",
  "Bissara":                           "$",
  "Rfissa":                            "$$",
  "Bastilla":                          "$$$",
  "Moroccan Chickpea and Spinach Stew":"$",
  "Mrouzia":                           "$$$",
  "Mechoui":                           "$$$",

  // ── Japanese ─────────────────────────────────────────────────────────────
  "Tonkotsu Ramen":   "$$$",
  "Karaage Chicken":  "$$",
  "Gyoza":            "$$",
  "Teriyaki Salmon":  "$$$",
  "Miso Soup":        "$",
  "Yakitori":         "$$",
  "Okonomiyaki":      "$$",
  "Japanese Curry":   "$$",
  "Cold Soba Noodles":"$",
  "Tamagoyaki":       "$",
  "Onigiri":          "$",
  "Korokke":          "$",
  "Oyakodon":         "$",
  "Tempura Udon":     "$$",
  "Katsu Sando":      "$$",

  // ── Mexican ──────────────────────────────────────────────────────────────
  "Tacos al Pastor":  "$$",
  "Guacamole":        "$",
  "Chicken Enchiladas":"$$",
  "Carnitas":         "$$",
  "Quesadillas":      "$",
  "Birria Tacos":     "$$$",
  "Elote":            "$",
  "Chilaquiles":      "$",
  "Pozole Rojo":      "$$",
  "Pico de Gallo":    "$",
  "Tamales":          "$$",
  "Flan":             "$",
  "Sopa de Lima":     "$$",
  "Chiles Rellenos":  "$$",
  "Huevos Rancheros": "$",

  // ── Indian ───────────────────────────────────────────────────────────────
  "Butter Chicken":       "$$",
  "Palak Paneer":         "$$",
  "Chicken Biryani":      "$$",
  "Dal Tadka":            "$",
  "Chana Masala":         "$",
  "Samosas":              "$",
  "Garlic Naan":          "$",
  "Aloo Gobi":            "$",
  "Lamb Rogan Josh":      "$$$",
  "Paneer Tikka Masala":  "$$",
  "Masala Dosa":          "$",
  "Kheer":                "$",
  "Mango Lassi":          "$",
  "Saag Aloo":            "$",
  "Raita":                "$",

  // ── Thai ─────────────────────────────────────────────────────────────────
  "Pad Thai":         "$$",
  "Thai Green Curry": "$$",
  "Tom Yum Soup":     "$$",
  "Massaman Curry":   "$$",
  "Pad See Ew":       "$$",
  "Som Tum":          "$",
  "Thai Fried Rice":  "$",
  "Chicken Satay":    "$$",
  "Thai Red Curry":   "$$",
  "Tom Kha Gai":      "$$",
  "Larb":             "$$",
  "Mango Sticky Rice":"$",
  "Khai Jiao":        "$",
  "Pad Kra Pao":      "$",
  "Thai Fish Cakes":  "$$",

  // ── General (popular recipes) ─────────────────────────────────────────────
  "Spaghetti Bolognese":   "$$",
  "Pasta Aglio e Olio":    "$",
  "Grilled Salmon":        "$$$",
  "Chicken Stir Fry":      "$$",
  "Vegetable Curry":       "$",
  "Omelette":              "$",
  "Caesar Salad":          "$$",
  "Beef Tacos":            "$$",
  "Mushroom Risotto":      "$$",
  "French Toast":          "$",
  "Shakshuka":             "$",
  "Chicken Tikka Masala":  "$$",
  "Fried Rice":            "$",
  "Avocado Toast":         "$",
  "Grilled Cheese":        "$",
  "Lentil Soup":           "$",
  "Pancakes":              "$",
};
