import type { Recipe } from "./recipes";

export const CUISINE_RECIPES: Recipe[] = [

  // ── ITALIAN ──────────────────────────────────────────────────────────────

  {
    name: "Pasta Carbonara",
    emoji: "🥚",
    description: "Silky egg sauce, crispy guanciale, and pecorino. Rome's greatest gift.",
    time: 20, difficulty: "Medium",
    dietary: [],
    key_ingredients: ["pasta", "eggs", "bacon", "parmesan"],
    extra_ingredients: ["black pepper", "salt"],
    steps: [
      "Cook pasta in heavily salted water. Reserve 1 cup pasta water before draining.",
      "Fry diced guanciale or bacon until crispy. Remove from heat.",
      "Whisk eggs with grated pecorino and a LOT of black pepper.",
      "Toss hot pasta with bacon, then egg mixture completely off heat. Add pasta water to make it creamy.",
    ],
    gremlin_note: "OFF the heat when adding eggs. Scrambled egg pasta is not carbonara.",
    cuisine: "Italian", level: "Intermediate", servings: 2, calories: 520,
  },
  {
    name: "Pasta all'Amatriciana",
    emoji: "🍅",
    description: "Spicy tomato sauce with crispy guanciale. The Roman classic before carbonara.",
    time: 25, difficulty: "Easy",
    dietary: ["halal"],
    key_ingredients: ["pasta", "tomatoes", "bacon", "onion"],
    extra_ingredients: ["chili flakes", "pecorino", "olive oil", "salt"],
    steps: [
      "Fry diced guanciale or bacon until crispy. Add sliced onion and cook until soft.",
      "Add chili flakes and crushed tomatoes. Simmer 15 minutes.",
      "Cook pasta in salted water, drain, toss with sauce.",
      "Serve topped with grated pecorino.",
    ],
    gremlin_note: "Use guanciale if you can find it. The fat is different and better.",
    cuisine: "Italian", level: "Beginner", servings: 2, calories: 490,
  },
  {
    name: "Saffron Risotto",
    emoji: "🌼",
    description: "Golden, creamy saffron-scented risotto. Milan's most famous dish.",
    time: 35, difficulty: "Medium",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["rice", "saffron", "parmesan", "onion"],
    extra_ingredients: ["white wine", "butter", "vegetable stock", "salt"],
    steps: [
      "Bloom saffron in a ladle of warm stock for 5 minutes.",
      "Sauté diced onion in butter, add rice and stir to coat. Add wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring constantly until absorbed before adding more.",
      "After 20 minutes, stir in saffron stock, cold butter, and parmesan. Season and serve immediately.",
    ],
    gremlin_note: "Warm stock only. Cold stock shocks the rice and ruins the texture.",
    cuisine: "Italian", level: "Intermediate", servings: 2, calories: 480,
  },
  {
    name: "Pollo alla Cacciatore",
    emoji: "🍗",
    description: "Hunter's chicken — braised with tomatoes, olives, and capers.",
    time: 45, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "tomatoes", "olives", "onion"],
    extra_ingredients: ["capers", "garlic", "olive oil", "rosemary", "white wine"],
    steps: [
      "Brown chicken pieces in olive oil on all sides. Remove.",
      "Sauté onion and garlic in same pan. Add tomatoes, olives, capers, rosemary, and wine.",
      "Return chicken to pan, cover, and simmer 30 minutes until cooked through.",
      "Adjust seasoning and serve with crusty bread or polenta.",
    ],
    gremlin_note: "The olives are non-negotiable. They make the whole dish.",
    cuisine: "Italian", level: "Beginner", servings: 4, calories: 380,
  },
  {
    name: "Pizza Margherita",
    emoji: "🍕",
    description: "Thin crispy base, crushed tomatoes, mozzarella, basil. Perfection.",
    time: 30, difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["flour", "tomatoes", "mozzarella"],
    extra_ingredients: ["yeast", "salt", "olive oil", "basil", "sugar"],
    steps: [
      "Mix flour, yeast, salt, olive oil, and warm water. Knead 8 minutes, rest 1 hour.",
      "Stretch dough thin on a floured surface. Top with crushed tomatoes and torn mozzarella.",
      "Bake at the highest oven temperature possible (250°C+) for 8–10 minutes.",
      "Add fresh basil and a drizzle of olive oil right after baking.",
    ],
    gremlin_note: "Hottest oven possible. This is not the time to be conservative.",
    cuisine: "Italian", level: "Intermediate", servings: 2, calories: 560,
  },
  {
    name: "Focaccia",
    emoji: "🫓",
    description: "Pillowy olive oil bread with dimples and a crispy crust. Dangerous to have in the house.",
    time: 90, difficulty: "Medium",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    key_ingredients: ["flour", "olive oil"],
    extra_ingredients: ["yeast", "salt", "rosemary", "flaky salt"],
    steps: [
      "Mix flour, yeast, salt, 4 tbsp olive oil, and warm water into a shaggy dough. Rest 1 hour.",
      "Pour olive oil into a baking pan, stretch dough in. Drizzle more oil on top. Rest 30 minutes.",
      "Dimple aggressively with your fingers, top with rosemary and flaky salt.",
      "Bake at 220°C/425°F for 20–25 minutes until deep golden.",
    ],
    gremlin_note: "More olive oil than you think. You want it pooling in the dimples.",
    cuisine: "Italian", level: "Intermediate", servings: 6, calories: 290,
  },
  {
    name: "Saltimbocca",
    emoji: "🥩",
    description: "Veal or chicken with prosciutto and sage, pan-fried in butter and white wine.",
    time: 20, difficulty: "Easy",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["chicken", "sage", "prosciutto"],
    extra_ingredients: ["butter", "white wine", "salt", "pepper", "toothpicks"],
    steps: [
      "Flatten chicken breasts thin. Lay a sage leaf and slice of prosciutto on top, secure with a toothpick.",
      "Pan fry prosciutto-side down in butter over medium-high heat for 3 minutes until crispy.",
      "Flip and cook 2 more minutes. Remove to a plate.",
      "Deglaze pan with white wine, reduce 1 minute, pour over chicken.",
    ],
    gremlin_note: "Prosciutto side down first so it crisps up. That's the whole point.",
    cuisine: "Italian", level: "Beginner", servings: 2, calories: 310,
  },
  {
    name: "Ribollita",
    emoji: "🥣",
    description: "Thick Tuscan bean and bread stew. Poor food that somehow beats everything else.",
    time: 45, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    key_ingredients: ["cannellini beans", "vegetables", "bread", "tomatoes"],
    extra_ingredients: ["kale", "onion", "garlic", "olive oil", "rosemary", "salt"],
    steps: [
      "Sauté diced onion, carrot, celery in olive oil until soft.",
      "Add garlic, tomatoes, cannellini beans, kale, rosemary, and 4 cups water. Simmer 25 minutes.",
      "Add thick slices of stale bread and push them into the soup. Simmer 10 more minutes.",
      "Drizzle generously with olive oil and serve hot or at room temperature.",
    ],
    gremlin_note: "Day-old bread is better than fresh. Stale bread thickens it beautifully.",
    cuisine: "Italian", level: "Beginner", servings: 4, calories: 340,
  },
  {
    name: "Tiramisu",
    emoji: "☕",
    description: "Coffee-soaked ladyfingers layered with mascarpone cream. No baking required.",
    time: 25, difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["mascarpone", "eggs", "coffee", "ladyfingers"],
    extra_ingredients: ["sugar", "cocoa powder", "Marsala or rum"],
    steps: [
      "Separate eggs. Whisk yolks with sugar until pale, fold in mascarpone.",
      "Whisk egg whites to stiff peaks, gently fold into mascarpone mixture.",
      "Dip ladyfingers briefly in strong coffee (and alcohol if using), line a dish.",
      "Layer cream, then ladyfingers, then cream. Dust with cocoa powder. Chill 4+ hours.",
    ],
    gremlin_note: "BRIEF dip in coffee — soggy ladyfingers ruin everything. One second per side.",
    cuisine: "Italian", level: "Intermediate", servings: 6, calories: 420,
  },
  {
    name: "Potato Gnocchi",
    emoji: "🥟",
    description: "Pillowy potato dumplings that melt in your mouth. Requires patience but worth it.",
    time: 60, difficulty: "Hard",
    dietary: ["vegetarian"],
    key_ingredients: ["potatoes", "flour", "eggs"],
    extra_ingredients: ["salt", "nutmeg", "butter", "sage"],
    steps: [
      "Bake potatoes until soft, rice them while hot. Cool completely.",
      "Add flour, egg yolk, salt, and nutmeg. Mix gently until just combined — don't overwork.",
      "Roll into ropes, cut into small pieces, roll over a fork to get grooves.",
      "Boil in salted water until they float (2 min). Toss in brown butter with sage.",
    ],
    gremlin_note: "Less flour than you think, more gentleness than you think. Overworked gnocchi = rubber.",
    cuisine: "Italian", level: "Pro", servings: 4, calories: 380,
  },
  {
    name: "Panzanella",
    emoji: "🥗",
    description: "Tuscan bread salad with ripe tomatoes and basil. No cooking needed.",
    time: 15, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    key_ingredients: ["tomatoes", "bread", "basil", "cucumber"],
    extra_ingredients: ["red onion", "olive oil", "red wine vinegar", "salt", "pepper"],
    steps: [
      "Tear stale bread into chunks, toast lightly or leave to dry out.",
      "Dice tomatoes and cucumber, thinly slice red onion.",
      "Toss everything together with olive oil, vinegar, salt, and basil.",
      "Let sit 15 minutes before eating — the bread absorbs the dressing.",
    ],
    gremlin_note: "Ripe tomatoes only. Watery supermarket tomatoes will betray you.",
    cuisine: "Italian", level: "Beginner", servings: 2, calories: 280,
  },
  {
    name: "Pasta e Fagioli",
    emoji: "🫘",
    description: "Thick pasta and bean soup that is somehow a complete life experience.",
    time: 35, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["pasta", "beans", "tomatoes", "garlic"],
    extra_ingredients: ["onion", "rosemary", "olive oil", "parmesan", "salt"],
    steps: [
      "Sauté garlic and onion in olive oil with rosemary until soft.",
      "Add crushed tomatoes and cannellini beans. Simmer 10 minutes.",
      "Mash some beans to thicken. Add stock and bring to boil.",
      "Add pasta and cook until just done. Finish with olive oil and parmesan.",
    ],
    gremlin_note: "Mash a third of the beans. Half-smooth, half-chunky is the texture you want.",
    cuisine: "Italian", level: "Beginner", servings: 4, calories: 390,
  },
  {
    name: "Bistecca alla Fiorentina",
    emoji: "🥩",
    description: "A massive T-bone steak grilled over high heat. The Florentine steak is a religion.",
    time: 15, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["steak", "rosemary", "garlic"],
    extra_ingredients: ["olive oil", "salt", "pepper", "lemon"],
    steps: [
      "Bring steak to room temperature. Season very generously with salt.",
      "Grill over the highest possible heat, 3 minutes per side — NO pressing.",
      "Rest 5 minutes, then drizzle with olive oil and lemon.",
      "Slice and serve with rosemary-rubbed bread and white beans.",
    ],
    gremlin_note: "Italians cook this rare-to-medium-rare. It's not negotiable in Florence.",
    cuisine: "Italian", level: "Beginner", servings: 2, calories: 650,
  },
  {
    name: "Arancini",
    emoji: "🟡",
    description: "Crispy golden rice balls with a melted cheese centre. Sicily's greatest snack.",
    time: 60, difficulty: "Hard",
    dietary: ["vegetarian"],
    key_ingredients: ["rice", "mozzarella", "parmesan", "eggs"],
    extra_ingredients: ["breadcrumbs", "saffron", "tomato paste", "salt", "oil for frying"],
    steps: [
      "Make saffron risotto (cook rice with stock, saffron, butter, parmesan). Cool completely.",
      "Shape cooled rice into balls around a cube of mozzarella.",
      "Coat in flour, beaten egg, then breadcrumbs.",
      "Deep fry at 180°C until deep golden and crispy all over, about 4 minutes.",
    ],
    gremlin_note: "The rice must be cold. Hot rice won't hold shape. Make it the day before ideally.",
    cuisine: "Italian", level: "Pro", servings: 12, calories: 180,
  },
  {
    name: "Osso Buco",
    emoji: "🦴",
    description: "Braised veal or beef shanks in white wine and vegetables. Milan's finest slow cook.",
    time: 120, difficulty: "Hard",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["beef shank", "tomatoes", "onion", "carrot"],
    extra_ingredients: ["celery", "white wine", "garlic", "gremolata", "butter", "flour", "stock"],
    steps: [
      "Dust shanks in flour, brown in butter and oil on all sides. Remove.",
      "Sauté onion, carrot, celery in same pot. Add garlic and tomato paste.",
      "Return shanks, add wine and stock to half-cover. Cover and braise 1.5 hours.",
      "Top with gremolata (lemon zest, garlic, parsley) and serve with risotto or polenta.",
    ],
    gremlin_note: "The marrow in the bone is the prize. Scoop it out with a spoon and spread on bread.",
    cuisine: "Italian", level: "Pro", servings: 4, calories: 510,
  },

  // ── MOROCCAN ─────────────────────────────────────────────────────────────

  {
    name: "Chicken Tagine",
    emoji: "🫕",
    description: "Slow-cooked chicken with preserved lemon and olives. The quintessential Moroccan dish.",
    time: 60, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "preserved lemon", "olives", "onion"],
    extra_ingredients: ["garlic", "ginger", "saffron", "turmeric", "coriander", "olive oil", "salt"],
    steps: [
      "Marinate chicken with garlic, ginger, saffron, turmeric, salt, and olive oil for 30 minutes.",
      "Brown chicken in a heavy pot or tagine on all sides. Remove.",
      "Cook sliced onions in same pot until golden. Return chicken, add a cup of water.",
      "Simmer covered 40 minutes. Add preserved lemon strips and olives for last 10 minutes.",
    ],
    gremlin_note: "Preserved lemon is the soul of this dish. Rinse it first, use only the skin.",
    cuisine: "Moroccan", level: "Intermediate", servings: 4, calories: 380,
  },
  {
    name: "Lamb Tagine with Prunes",
    emoji: "🍖",
    description: "Sweet and savory slow-braised lamb with prunes, almonds, and cinnamon.",
    time: 90, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["lamb", "prunes", "almonds", "onion"],
    extra_ingredients: ["honey", "cinnamon", "ginger", "saffron", "butter", "salt", "sesame seeds"],
    steps: [
      "Brown lamb chunks in oil. Add onion, ginger, saffron, cinnamon, salt, and water.",
      "Cover and simmer 1 hour until lamb is tender.",
      "Add prunes and honey. Cook uncovered 15 minutes until sauce thickens.",
      "Toast almonds in butter, scatter over with sesame seeds to serve.",
    ],
    gremlin_note: "The sweetness from the prunes and honey is meant to be there — trust the recipe.",
    cuisine: "Moroccan", level: "Intermediate", servings: 4, calories: 480,
  },
  {
    name: "Harira",
    emoji: "🥣",
    description: "The iconic Moroccan soup — tomatoes, lentils, chickpeas, and lamb. Eaten to break the Ramadan fast.",
    time: 50, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["tomatoes", "chickpeas", "lentils", "lamb"],
    extra_ingredients: ["celery", "onion", "coriander", "parsley", "saffron", "flour", "lemon", "salt"],
    steps: [
      "Brown lamb cubes with onion, celery, saffron, and salt in a large pot.",
      "Add crushed tomatoes, lentils, chickpeas, coriander, parsley, and 6 cups water.",
      "Simmer 30 minutes until lentils are soft.",
      "Mix flour with water to make a slurry, stir in to thicken. Add lemon juice.",
    ],
    gremlin_note: "The flour slurry at the end is what makes Harira Harira. Don't skip it.",
    cuisine: "Moroccan", level: "Beginner", servings: 6, calories: 310,
  },
  {
    name: "Kefta Tagine",
    emoji: "🍳",
    description: "Spiced ground meat meatballs simmered in tomato sauce with eggs cracked on top.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["ground beef", "tomatoes", "eggs", "onion"],
    extra_ingredients: ["cumin", "paprika", "cinnamon", "parsley", "olive oil", "salt"],
    steps: [
      "Mix ground beef with grated onion, cumin, paprika, cinnamon, parsley, and salt. Form small meatballs.",
      "Brown meatballs in olive oil in a tagine or wide pan.",
      "Add crushed tomatoes and simmer 15 minutes.",
      "Make wells, crack in eggs, cover and cook 5 minutes until whites are just set.",
    ],
    gremlin_note: "Runny yolks. Always runny yolks. Break them into the sauce at the table.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 390,
  },
  {
    name: "Zaalouk",
    emoji: "🍆",
    description: "Smoky roasted eggplant and tomato salad. A staple Moroccan starter.",
    time: 30, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["eggplant", "tomatoes", "garlic"],
    extra_ingredients: ["cumin", "paprika", "olive oil", "parsley", "lemon", "salt"],
    steps: [
      "Roast eggplants whole at 200°C/400°F until collapsed and soft, about 20 minutes.",
      "Peel, chop, and squeeze out excess water.",
      "Cook with crushed tomatoes, garlic, cumin, paprika, and olive oil for 10 minutes.",
      "Mash together, add lemon juice and parsley. Serve warm or cold.",
    ],
    gremlin_note: "Roasting the eggplant whole gives a smoky depth. Don't skip that step.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 120,
  },
  {
    name: "Chermoula Fish",
    emoji: "🐟",
    description: "Fish marinated in the classic Moroccan chermoula sauce then pan-fried or baked.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["fish", "garlic", "coriander", "cumin"],
    extra_ingredients: ["paprika", "lemon", "olive oil", "parsley", "salt"],
    steps: [
      "Blend garlic, fresh coriander, cumin, paprika, lemon juice, olive oil, and salt into chermoula paste.",
      "Score fish fillets and rub chermoula all over. Marinate 20 minutes.",
      "Pan-fry in olive oil 3–4 minutes per side until golden and cooked through.",
      "Serve with lemon and crusty bread.",
    ],
    gremlin_note: "Chermoula works on any fish, chicken, or vegetables. Make extra and keep it.",
    cuisine: "Moroccan", level: "Beginner", servings: 2, calories: 280,
  },
  {
    name: "Couscous with Seven Vegetables",
    emoji: "🫙",
    description: "The Friday dish in Morocco — fluffy couscous with slow-stewed vegetables and chickpeas.",
    time: 60, difficulty: "Medium",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["couscous", "chickpeas", "vegetables", "onion"],
    extra_ingredients: ["saffron", "turmeric", "cumin", "olive oil", "salt", "butter"],
    steps: [
      "Steam couscous per package, fluffing with oil and butter between steamings.",
      "Simmer chickpeas with onion, saffron, turmeric, cumin, and salt in stock.",
      "Add vegetables in order of density: turnip, carrot first, then zucchini, tomatoes last.",
      "Mound couscous on a platter, top with vegetables and broth.",
    ],
    gremlin_note: "Steam couscous ABOVE the stew if possible so it absorbs the aromatics.",
    cuisine: "Moroccan", level: "Intermediate", servings: 6, calories: 340,
  },
  {
    name: "Taktouka",
    emoji: "🫑",
    description: "Slow-cooked roasted peppers and tomatoes in olive oil. A stunning simple salad.",
    time: 25, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["roasted peppers", "tomatoes", "garlic"],
    extra_ingredients: ["cumin", "paprika", "olive oil", "parsley", "salt"],
    steps: [
      "Roast peppers directly over flame or under broiler until charred. Peel, deseed, and slice.",
      "Peel and dice tomatoes. Cook with garlic in olive oil 10 minutes.",
      "Add peppers, cumin, paprika. Cook 10 more minutes until thick.",
      "Finish with parsley and serve warm or cold.",
    ],
    gremlin_note: "Charring the peppers over the flame is what gives it that depth. Do it properly.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 130,
  },
  {
    name: "Moroccan Carrot Salad",
    emoji: "🥕",
    description: "Warm spiced carrots with cumin, honey and lemon. Somehow better than it sounds.",
    time: 15, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["carrots", "cumin", "lemon", "garlic"],
    extra_ingredients: ["olive oil", "honey", "paprika", "coriander", "salt"],
    steps: [
      "Boil or steam sliced carrots until just tender. Drain.",
      "Warm olive oil with garlic, cumin, and paprika for 1 minute.",
      "Toss carrots in spiced oil with lemon juice, honey, and coriander.",
      "Serve warm or at room temperature.",
    ],
    gremlin_note: "Slightly undercook the carrots — they should have a tiny bite, not be mushy.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 110,
  },
  {
    name: "Bissara",
    emoji: "🫛",
    description: "Silky dried fava bean soup with cumin and paprika oil. Moroccan street food staple.",
    time: 45, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["dried fava beans", "garlic", "cumin"],
    extra_ingredients: ["olive oil", "paprika", "lemon", "salt", "chili flakes"],
    steps: [
      "Soak dried fava beans overnight. Drain and peel skins off.",
      "Simmer beans with garlic and salt in water until completely soft, about 35 minutes.",
      "Blend or mash until very smooth. Thin with water to soup consistency.",
      "Serve in bowls topped with olive oil, cumin, paprika, and lemon juice.",
    ],
    gremlin_note: "The cumin and olive oil drizzled on top at serving is everything here.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 220,
  },
  {
    name: "Rfissa",
    emoji: "🍲",
    description: "Chicken slow-cooked with lentils and fenugreek over torn flatbread. The special occasion dish.",
    time: 75, difficulty: "Medium",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken", "lentils", "onion", "bread"],
    extra_ingredients: ["fenugreek", "ginger", "saffron", "ras el hanout", "butter", "salt"],
    steps: [
      "Brown chicken pieces in butter with onion, ginger, saffron, ras el hanout, and salt.",
      "Add lentils and fenugreek seeds with 4 cups water. Simmer covered 45 minutes.",
      "Tear msemen flatbread (or use pita) into pieces and spread on a large platter.",
      "Pour chicken, lentils, and broth over the bread and serve family-style.",
    ],
    gremlin_note: "Fenugreek seeds have a strong flavor — don't use more than the recipe says.",
    cuisine: "Moroccan", level: "Intermediate", servings: 6, calories: 440,
  },
  {
    name: "Bastilla",
    emoji: "🥧",
    description: "Flaky pastry stuffed with spiced chicken and almonds. Sweet and savory in one bite.",
    time: 90, difficulty: "Hard",
    dietary: ["halal"],
    key_ingredients: ["chicken", "almonds", "eggs", "pastry sheets"],
    extra_ingredients: ["onion", "cinnamon", "ginger", "saffron", "sugar", "parsley", "butter"],
    steps: [
      "Poach chicken with onion, saffron, ginger, and cinnamon. Shred when cool.",
      "Reduce cooking liquid, add eggs and scramble into sauce. Mix with parsley.",
      "Toast and roughly crush almonds with sugar and cinnamon.",
      "Layer buttered pastry sheets, add chicken, then almonds, fold over. Bake at 190°C until golden. Dust with powdered sugar.",
    ],
    gremlin_note: "The sweet-savory contrast is the whole point. Don't be scared of the powdered sugar on top.",
    cuisine: "Moroccan", level: "Pro", servings: 8, calories: 420,
  },
  {
    name: "Moroccan Chickpea and Spinach Stew",
    emoji: "🥬",
    description: "Fast weeknight Moroccan — chickpeas and spinach in spiced tomato broth.",
    time: 25, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chickpeas", "spinach", "tomatoes", "garlic"],
    extra_ingredients: ["onion", "cumin", "paprika", "cinnamon", "olive oil", "lemon", "salt"],
    steps: [
      "Sauté onion and garlic in olive oil until soft. Add cumin, paprika, and cinnamon.",
      "Add crushed tomatoes and drained chickpeas. Simmer 10 minutes.",
      "Stir in spinach and cook until wilted.",
      "Squeeze lemon over, season, and serve with crusty bread.",
    ],
    gremlin_note: "Add the lemon at the end, not before — acid turns spinach an ugly colour if cooked.",
    cuisine: "Moroccan", level: "Beginner", servings: 4, calories: 260,
  },
  {
    name: "Mrouzia",
    emoji: "🍯",
    description: "Slow-braised lamb with honey, almonds and ras el hanout. Festive and deeply aromatic.",
    time: 100, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["lamb", "honey", "almonds", "onion"],
    extra_ingredients: ["ras el hanout", "cinnamon", "ginger", "butter", "raisins", "salt"],
    steps: [
      "Brown lamb pieces in butter with onion, ras el hanout, cinnamon, ginger, and salt.",
      "Add water to just cover. Simmer covered 1 hour until lamb is very tender.",
      "Uncover, add honey, raisins, and toasted almonds. Simmer until sauce is glossy.",
      "Serve over couscous or with bread.",
    ],
    gremlin_note: "Ras el hanout is the key spice — it's a complex blend, no single substitute.",
    cuisine: "Moroccan", level: "Intermediate", servings: 6, calories: 520,
  },
  {
    name: "Mechoui",
    emoji: "🐑",
    description: "Slow-roasted spiced lamb shoulder that falls off the bone. A Moroccan celebration dish.",
    time: 180, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["lamb shoulder", "garlic", "cumin", "butter"],
    extra_ingredients: ["paprika", "coriander", "turmeric", "salt"],
    steps: [
      "Blend garlic, cumin, paprika, coriander, turmeric, and soft butter into a paste.",
      "Score lamb shoulder deeply and rub the paste all over and into the cuts.",
      "Roast at 160°C/320°F for 3 hours, basting occasionally, until falling apart tender.",
      "Serve with coarse salt, cumin, and flatbread for wrapping.",
    ],
    gremlin_note: "Patience. Three hours at low heat is not optional. Fast roasting ruins mechoui.",
    cuisine: "Moroccan", level: "Intermediate", servings: 8, calories: 580,
  },
];
