import type { Recipe } from "./recipes";

export const CUISINE_RECIPES_2: Recipe[] = [

  // ── JAPANESE ──────────────────────────────────────────────────────────────

  {
    name: "Tonkotsu Ramen",
    emoji: "🍜",
    description: "Rich, cloudy pork bone broth with chewy noodles, chashu pork, and a marinated soft-boiled egg.",
    time: 240, difficulty: "Hard",
    dietary: ["dairy-free"],
    key_ingredients: ["pork belly", "ramen noodles", "eggs", "soy sauce"],
    extra_ingredients: ["pork bones", "garlic", "ginger", "mirin", "sake", "nori", "green onion", "sesame oil"],
    steps: [
      "Blanch pork bones in boiling water 5 min, drain, then simmer in 3L fresh water for 3–4 hours until broth is milky. Season with salt.",
      "Braise pork belly in soy sauce, mirin, sake, garlic, and ginger for 1.5 hours. Cool, then slice.",
      "Soft-boil eggs 7 min, peel, marinate in 1:1 soy sauce and mirin for 1 hour minimum.",
      "Cook ramen noodles per package. Ladle hot broth into bowls, add noodles, sliced pork, halved egg, nori, and green onion.",
    ],
    gremlin_note: "The broth must coat the back of a spoon. If it's watery, simmer longer uncovered.",
    cuisine: "Japanese", level: "Pro", servings: 4, calories: 620,
  },
  {
    name: "Karaage Chicken",
    emoji: "🍗",
    description: "Japanese fried chicken — juicy inside, shatteringly crispy outside, with a ginger-soy marinade.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken thighs", "soy sauce", "ginger", "garlic"],
    extra_ingredients: ["sake", "sesame oil", "potato starch", "oil for frying", "lemon", "mayonnaise"],
    steps: [
      "Cut chicken thighs into chunks. Marinate in soy sauce, sake, grated ginger, garlic, and sesame oil for 20 min.",
      "Coat chicken pieces thoroughly in potato starch.",
      "Fry in 170°C oil for 3 min, remove and rest 3 min, then fry again at 190°C for 1 min until extra crispy.",
      "Drain and serve with lemon wedges and Japanese mayo.",
    ],
    gremlin_note: "The double-fry is non-negotiable. First fry cooks it, second fry makes it shatter.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 480,
  },
  {
    name: "Gyoza",
    emoji: "🥟",
    description: "Pan-fried Japanese dumplings — crispy on the bottom, steamed on top, filled with pork and cabbage.",
    time: 45, difficulty: "Medium",
    dietary: ["dairy-free"],
    key_ingredients: ["ground pork", "cabbage", "garlic", "ginger"],
    extra_ingredients: ["dumpling wrappers", "soy sauce", "sesame oil", "green onion", "rice vinegar", "chili oil"],
    steps: [
      "Finely shred cabbage, salt it, squeeze out as much water as possible. Mix with pork, garlic, ginger, green onion, soy sauce, sesame oil.",
      "Place a spoonful of filling in each wrapper, moisten edges, fold and pleat to seal.",
      "Heat oil in a pan, add gyoza flat-side down. Fry until golden on the base, 2–3 min.",
      "Add a splash of water, cover immediately, steam 3 min. Remove lid, let water evaporate. Serve with dipping sauce.",
    ],
    gremlin_note: "Squeeze the cabbage dry aggressively. Wet filling = soggy gyoza. Use both hands.",
    cuisine: "Japanese", level: "Intermediate", servings: 4, calories: 320,
  },
  {
    name: "Teriyaki Salmon",
    emoji: "🐟",
    description: "Salmon glazed in a sweet-savory teriyaki sauce. Ready in 20 minutes, tastes like a restaurant.",
    time: 20, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free"],
    key_ingredients: ["salmon", "soy sauce", "mirin", "honey"],
    extra_ingredients: ["garlic", "ginger", "sesame seeds", "green onion", "rice"],
    steps: [
      "Mix soy sauce, mirin, honey, garlic, and ginger into a teriyaki glaze.",
      "Pat salmon dry and season with salt and pepper.",
      "Sear skin-side down in an oiled pan over medium-high heat for 4 min. Flip.",
      "Pour glaze over salmon, cook 2–3 min, spooning sauce over it repeatedly until glossy. Serve over rice with sesame seeds.",
    ],
    gremlin_note: "Don't touch the salmon for those first 4 minutes. Let the crust form — it will release itself.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 420,
  },
  {
    name: "Miso Soup",
    emoji: "🥣",
    description: "The most comforting bowl in Japanese cooking. Silky tofu, seaweed, and a deeply savory broth.",
    time: 10, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    key_ingredients: ["miso paste", "tofu", "seaweed"],
    extra_ingredients: ["dashi stock or water", "green onion", "wakame"],
    steps: [
      "Heat dashi (or water with dashi powder) to just below a simmer — never boil miso.",
      "Dissolve miso paste in a ladle of the warm dashi, then stir back into the pot.",
      "Add cubed silken tofu and rehydrated wakame seaweed. Heat gently for 1 min.",
      "Serve immediately, topped with sliced green onion.",
    ],
    gremlin_note: "Miso dies above 60°C. Boiling kills the flavor and probiotics. Warm, don't cook.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 80,
  },
  {
    name: "Yakitori",
    emoji: "🍢",
    description: "Grilled chicken skewers basted in a sweet soy glaze. Tokyo street food at its finest.",
    time: 25, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken thighs", "soy sauce", "mirin", "sake"],
    extra_ingredients: ["sugar", "green onion", "bamboo skewers", "sesame seeds"],
    steps: [
      "Mix soy sauce, mirin, sake, and sugar in a pan. Simmer until slightly thickened — this is your tare.",
      "Cut chicken into chunks, thread onto skewers alternating with green onion pieces.",
      "Grill or pan-fry on high heat, turning frequently. Baste with tare every minute for the last 3 min.",
      "Finish with a final brush of tare and sesame seeds.",
    ],
    gremlin_note: "Baste in layers — each pass builds up a lacquered coating. One coat is not enough.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 350,
  },
  {
    name: "Okonomiyaki",
    emoji: "🥞",
    description: "Japanese savory pancake packed with cabbage and bacon, topped with sweet sauce and mayo.",
    time: 25, difficulty: "Medium",
    dietary: [],
    key_ingredients: ["flour", "eggs", "cabbage", "bacon"],
    extra_ingredients: ["dashi", "baking powder", "okonomiyaki sauce", "Japanese mayo", "bonito flakes", "nori flakes"],
    steps: [
      "Whisk flour, dashi, eggs, and baking powder into a batter. Fold in shredded cabbage — it should be mostly cabbage.",
      "Lay bacon strips in a pan over medium heat. Pour batter over bacon and shape into a round pancake.",
      "Cook 5–6 min until the base is set. Flip carefully, cook 4 more min.",
      "Drizzle okonomiyaki sauce and mayo, top with bonito flakes and nori. The bonito will wave in the heat.",
    ],
    gremlin_note: "More cabbage than you think — it cooks down. A soggy okonomiyaki is an under-cabbage okonomiyaki.",
    cuisine: "Japanese", level: "Intermediate", servings: 2, calories: 440,
  },
  {
    name: "Japanese Curry",
    emoji: "🍛",
    description: "Thick, mellow curry with chicken and vegetables. Japan's ultimate comfort food over sticky rice.",
    time: 35, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken", "potatoes", "carrots", "onion"],
    extra_ingredients: ["curry roux blocks", "garlic", "ginger", "soy sauce", "honey", "rice"],
    steps: [
      "Sauté diced onion until golden. Add chicken and brown on all sides.",
      "Add chopped carrots and potatoes, stir for 2 min.",
      "Pour in 600ml water, bring to boil, then simmer 15 min until vegetables are tender.",
      "Break in curry roux blocks, stir until dissolved. Add soy sauce and honey. Simmer 5 min until thick. Serve over rice.",
    ],
    gremlin_note: "Japanese curry roux blocks are the secret — they're in most Asian supermarkets. Don't substitute standard curry powder.",
    cuisine: "Japanese", level: "Beginner", servings: 4, calories: 520,
  },
  {
    name: "Cold Soba Noodles",
    emoji: "🍜",
    description: "Chilled buckwheat noodles served with a chilled dipping broth. Summer in a bowl.",
    time: 15, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    key_ingredients: ["soba noodles", "soy sauce", "mirin", "dashi"],
    extra_ingredients: ["green onion", "nori", "sesame seeds", "wasabi", "grated daikon"],
    steps: [
      "Cook soba noodles per package, drain, and rinse immediately under cold running water until chilled.",
      "Mix soy sauce, mirin, and dashi into a dipping broth. Chill in the fridge.",
      "Arrange noodles on a bamboo mat or plate, garnish with nori strips.",
      "Serve with dipping broth and condiments — dip each mouthful just before eating.",
    ],
    gremlin_note: "Rinse soba aggressively under cold water to remove starch or they'll clump into a gluey brick.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 380,
  },
  {
    name: "Tamagoyaki",
    emoji: "🥚",
    description: "Sweet Japanese rolled omelette — silky, delicate, and subtly flavored with mirin.",
    time: 15, difficulty: "Medium",
    dietary: ["vegetarian", "dairy-free"],
    key_ingredients: ["eggs", "mirin", "soy sauce"],
    extra_ingredients: ["sugar", "dashi", "oil"],
    steps: [
      "Whisk eggs with mirin, soy sauce, sugar, and a splash of dashi.",
      "Heat a rectangular or round pan with a little oil over medium-low.",
      "Pour in a thin layer of egg mixture. When just set, roll it to one side of the pan.",
      "Add another thin layer, lift the rolled egg and let the new layer run underneath, then roll again. Repeat until mixture is used. Press gently with a mat while warm to shape.",
    ],
    gremlin_note: "Low heat, patience, thin layers. Rushing the heat gives you scrambled eggs, not tamagoyaki.",
    cuisine: "Japanese", level: "Intermediate", servings: 2, calories: 180,
  },
  {
    name: "Onigiri",
    emoji: "🍙",
    description: "Japanese rice balls filled with salmon or tuna, wrapped in crispy nori. The perfect portable meal.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["short-grain rice", "nori", "salmon"],
    extra_ingredients: ["salt", "sesame seeds", "soy sauce", "mayonnaise"],
    steps: [
      "Cook short-grain rice and let it cool slightly — not cold, but handleable.",
      "Flake cooked or canned salmon and mix with a little mayo and soy sauce.",
      "Wet your hands, rub salt on your palms. Take a handful of rice, press flat, add filling, close and shape into a triangle.",
      "Press firmly so it holds, wrap in nori just before eating so it stays crispy.",
    ],
    gremlin_note: "Wrap the nori right before eating. Pre-wrapping makes it soggy in minutes.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 250,
  },
  {
    name: "Korokke",
    emoji: "🥔",
    description: "Japanese potato croquettes — crispy panko shell, creamy potato inside. Served with Worcestershire sauce.",
    time: 45, difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["potatoes", "onion", "breadcrumbs", "eggs"],
    extra_ingredients: ["butter", "flour", "panko", "oil for frying", "Worcestershire sauce", "black pepper"],
    steps: [
      "Boil potatoes until soft, drain, mash while hot with butter and seasoning.",
      "Sauté diced onion until soft and sweet, fold into mash. Cool completely.",
      "Shape into oval patties. Coat in flour, beaten egg, then panko breadcrumbs.",
      "Shallow fry in 170°C oil until deep golden on all sides, 3–4 min. Drain and serve with Worcestershire sauce.",
    ],
    gremlin_note: "Let the mash cool fully before shaping or it falls apart in the oil. Rushing this step is the classic korokke mistake.",
    cuisine: "Japanese", level: "Intermediate", servings: 4, calories: 390,
  },
  {
    name: "Oyakodon",
    emoji: "🍚",
    description: "Chicken and egg simmered in a sweet-savory dashi broth, poured over steaming rice.",
    time: 20, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken thighs", "eggs", "onion", "soy sauce"],
    extra_ingredients: ["mirin", "sake", "dashi", "sugar", "rice", "green onion"],
    steps: [
      "Simmer sliced onion in dashi, soy sauce, mirin, sake, and sugar for 3 min.",
      "Add sliced chicken thighs, cook 5 min until just cooked through.",
      "Beat eggs loosely and pour in a circular motion over the chicken. Cover and cook on low for 30 seconds — the egg should be just barely set.",
      "Slide over a bowl of hot rice. Top with green onion.",
    ],
    gremlin_note: "Semi-raw egg is the goal — it should still tremble when you tip the bowl. Overcooked is a tragedy.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 480,
  },
  {
    name: "Tempura Udon",
    emoji: "🍢",
    description: "Thick, chewy udon noodles in a clear dashi broth topped with crispy shrimp tempura.",
    time: 30, difficulty: "Medium",
    dietary: ["dairy-free"],
    key_ingredients: ["udon noodles", "shrimp", "flour", "dashi"],
    extra_ingredients: ["soy sauce", "mirin", "egg", "ice water", "nori", "green onion", "oil for frying"],
    steps: [
      "Make broth: simmer dashi with soy sauce and mirin. Keep warm.",
      "Make tempura batter: mix flour with ice cold egg water — keep it lumpy. Coat shrimp.",
      "Fry shrimp at 180°C until pale golden and crispy, 2–3 min. Drain on paper.",
      "Cook udon per package, drain, add to hot broth in bowls. Top with tempura, nori, and green onion.",
    ],
    gremlin_note: "Ice cold batter is everything. Warm batter goes soggy. Use ice cubes in the water bowl.",
    cuisine: "Japanese", level: "Intermediate", servings: 2, calories: 560,
  },
  {
    name: "Katsu Sando",
    emoji: "🥪",
    description: "Thick pork or chicken cutlet fried in panko, slathered in tonkatsu sauce, in soft white bread.",
    time: 25, difficulty: "Easy",
    dietary: ["dairy-free"],
    key_ingredients: ["pork loin", "panko breadcrumbs", "eggs", "white bread"],
    extra_ingredients: ["flour", "tonkatsu sauce", "mustard", "cabbage", "oil for frying"],
    steps: [
      "Pound pork loin to 1cm thickness. Season with salt and pepper.",
      "Coat in flour, beaten egg, then press firmly into panko breadcrumbs.",
      "Fry in 170°C oil for 4 min per side until deep golden. Drain and rest 2 min.",
      "Spread bread with butter and tonkatsu sauce. Add shredded cabbage, lay the cutlet, slice off crusts, cut in half.",
    ],
    gremlin_note: "Press the panko in firmly with both hands. Loose crumbs fall off in the oil and burn.",
    cuisine: "Japanese", level: "Beginner", servings: 2, calories: 580,
  },

  // ── MEXICAN ───────────────────────────────────────────────────────────────

  {
    name: "Tacos al Pastor",
    emoji: "🌮",
    description: "Spiced marinated chicken with pineapple, cilantro, and onion in warm tortillas.",
    time: 30, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "pineapple", "onion", "chipotle"],
    extra_ingredients: ["cumin", "oregano", "garlic", "lime", "corn tortillas", "cilantro", "achiote paste"],
    steps: [
      "Blend chipotle, achiote, cumin, oregano, garlic, lime juice, and pineapple into a marinade. Coat chicken and marinate 30 min.",
      "Grill or pan-fry chicken over high heat until charred at the edges and cooked through. Rest 3 min.",
      "Slice chicken and mix with grilled pineapple pieces.",
      "Warm tortillas directly on a flame or dry pan. Serve with onion, cilantro, and lime.",
    ],
    gremlin_note: "The char on the edges is the al pastor flavor — don't cook it over medium heat expecting that result.",
    cuisine: "Mexican", level: "Intermediate", servings: 4, calories: 420,
  },
  {
    name: "Guacamole",
    emoji: "🥑",
    description: "Perfectly chunky avocado dip with lime, jalapeño, and fresh cilantro. No blender needed.",
    time: 10, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["avocado", "lime", "tomato", "onion"],
    extra_ingredients: ["jalapeño", "cilantro", "garlic", "salt"],
    steps: [
      "Halve and pit avocados. Scoop flesh into a bowl.",
      "Add lime juice immediately and smash with a fork — keep it chunky.",
      "Fold in finely diced tomato, white onion, jalapeño, and cilantro.",
      "Season generously with salt. Taste. More lime, more salt. Always.",
    ],
    gremlin_note: "Ripe avocados only — they should give when pressed. Unripe avocado makes sad, plasticky guac.",
    cuisine: "Mexican", level: "Beginner", servings: 4, calories: 160,
  },
  {
    name: "Chicken Enchiladas",
    emoji: "🫔",
    description: "Rolled corn tortillas stuffed with chicken and cheese, smothered in red chile sauce.",
    time: 45, difficulty: "Medium",
    dietary: ["gluten-free"],
    key_ingredients: ["chicken", "corn tortillas", "tomatoes", "cheese"],
    extra_ingredients: ["onion", "garlic", "chili powder", "cumin", "sour cream", "dried chiles", "chicken broth"],
    steps: [
      "Simmer dried chiles (ancho, guajillo) in broth 10 min, blend with tomato, garlic, and cumin into a smooth sauce.",
      "Shred cooked chicken and mix with half the cheese.",
      "Briefly dip tortillas in sauce to soften. Fill with chicken, roll, and place seam-down in a baking dish.",
      "Pour remaining sauce over, top with rest of cheese. Bake at 190°C for 20 min. Serve with sour cream.",
    ],
    gremlin_note: "Dipping the tortillas in sauce before filling prevents them from cracking when you roll them.",
    cuisine: "Mexican", level: "Intermediate", servings: 4, calories: 520,
  },
  {
    name: "Carnitas",
    emoji: "🥩",
    description: "Slow-cooked pork shoulder pulled into tender, crispy-edged shreds. The king of taco fillings.",
    time: 120, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["pork shoulder", "orange", "garlic", "cumin"],
    extra_ingredients: ["oregano", "bay leaves", "salt", "lime", "corn tortillas", "cilantro", "onion"],
    steps: [
      "Cut pork into large chunks. Season with salt, cumin, and oregano.",
      "Simmer in a pot with orange juice, garlic, and bay leaves just barely covered with water for 1.5 hours until completely tender.",
      "Remove pork, shred roughly. Reduce the cooking liquid until syrupy.",
      "Spread pork on a baking tray, drizzle with reduced liquid. Broil for 5–7 min until edges char and crisp.",
    ],
    gremlin_note: "The broil step is where carnitas becomes carnitas — don't skip it. That char is the flavor.",
    cuisine: "Mexican", level: "Beginner", servings: 6, calories: 480,
  },
  {
    name: "Quesadillas",
    emoji: "🫓",
    description: "Crispy flour tortilla filled with melted cheese and peppers. The 15-minute weeknight hero.",
    time: 15, difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["flour tortillas", "cheese", "peppers"],
    extra_ingredients: ["onion", "jalapeño", "cumin", "sour cream", "salsa", "oil"],
    steps: [
      "Sauté diced peppers and onion until soft and slightly caramelized.",
      "Place a tortilla in a dry pan over medium heat. Add cheese on one half, then peppers.",
      "Fold over and press firmly with a spatula. Cook 2–3 min until golden, flip, cook 1 more min.",
      "Slice into wedges and serve with sour cream and salsa.",
    ],
    gremlin_note: "Low and slow on the heat — high heat burns the outside before the cheese melts.",
    cuisine: "Mexican", level: "Beginner", servings: 2, calories: 440,
  },
  {
    name: "Birria Tacos",
    emoji: "🌮",
    description: "Slow-braised beef in rich chile broth, served in crispy dipped tortillas with melted cheese.",
    time: 180, difficulty: "Hard",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["beef", "dried chiles", "tomatoes", "onion"],
    extra_ingredients: ["garlic", "cumin", "oregano", "vinegar", "corn tortillas", "cilantro", "lime", "cheese"],
    steps: [
      "Toast ancho, guajillo, and chipotle chiles in a dry pan, then soak in hot water 20 min. Blend with tomatoes, garlic, cumin, and oregano.",
      "Brown beef chunks in batches. Add chile sauce and enough water to cover. Braise covered 2.5 hours until fall-apart tender.",
      "Shred beef. Skim fat from the broth — this is your consommé for dipping.",
      "Dip tortillas in the consommé fat, fry in a pan, add beef and cheese, fold. Serve with consommé for dunking.",
    ],
    gremlin_note: "Dip the tortilla in the FAT floating on the broth, not the broth itself — it makes them crispy, not soggy.",
    cuisine: "Mexican", level: "Pro", servings: 6, calories: 580,
  },
  {
    name: "Elote",
    emoji: "🌽",
    description: "Mexican street corn — charred cob smothered in mayo, cheese, lime, and chili. Incredible.",
    time: 20, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["corn", "mayonnaise", "lime", "chili powder"],
    extra_ingredients: ["cotija cheese or feta", "butter", "cilantro", "garlic", "salt"],
    steps: [
      "Grill corn on the cob (or in a dry pan) over high heat, turning, until nicely charred in spots.",
      "Mix mayo with lime juice, garlic, and a pinch of chili powder.",
      "While still hot, brush corn generously with mayo mixture.",
      "Roll in crumbled cotija cheese, dust with more chili powder, and finish with cilantro and lime.",
    ],
    gremlin_note: "The char is essential — pale corn with mayo is just corn with mayo. Get real color on it.",
    cuisine: "Mexican", level: "Beginner", servings: 4, calories: 220,
  },
  {
    name: "Chilaquiles",
    emoji: "🍳",
    description: "Tortilla chips simmered in salsa until just softened, topped with eggs, cream, and cheese.",
    time: 25, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["tortilla chips", "salsa", "eggs", "cheese"],
    extra_ingredients: ["onion", "cream", "cilantro", "sour cream", "avocado"],
    steps: [
      "Warm salsa in a wide pan over medium heat for 2 min.",
      "Add tortilla chips and stir gently to coat. Let them absorb the salsa for 2–3 min — they should soften but not turn to mush.",
      "Make wells in the chips and crack eggs in. Cover and cook until whites are just set.",
      "Top with crumbled cheese, sour cream, and cilantro. Eat immediately.",
    ],
    gremlin_note: "Chips in the salsa for TWO minutes max. Any longer and you have a paste. Timing is everything.",
    cuisine: "Mexican", level: "Beginner", servings: 2, calories: 380,
  },
  {
    name: "Pozole Rojo",
    emoji: "🥣",
    description: "Hearty Mexican stew of chicken and hominy in a rich red chile broth. A celebration in a bowl.",
    time: 90, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "hominy", "dried chiles", "onion"],
    extra_ingredients: ["garlic", "cumin", "oregano", "lime", "radishes", "cabbage", "tostadas"],
    steps: [
      "Simmer chicken with half an onion and garlic until cooked through. Reserve broth, shred chicken.",
      "Toast ancho and guajillo chiles, soak in hot water, then blend with garlic and cumin. Fry paste in oil 3 min.",
      "Add chicken broth, hominy, and chicken to the chile paste. Simmer 30 min.",
      "Serve with shredded cabbage, sliced radishes, oregano, and lime. Let everyone build their own bowl.",
    ],
    gremlin_note: "Toast the chiles until fragrant but not black. Burnt chile makes the whole broth bitter.",
    cuisine: "Mexican", level: "Intermediate", servings: 6, calories: 320,
  },
  {
    name: "Pico de Gallo",
    emoji: "🍅",
    description: "Fresh tomato salsa with cilantro, lime, and jalapeño. Better than anything from a jar, always.",
    time: 10, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["tomatoes", "onion", "jalapeño", "cilantro"],
    extra_ingredients: ["lime", "salt", "garlic"],
    steps: [
      "Dice tomatoes and drain excess juice in a strainer — this keeps it fresh, not watery.",
      "Finely dice white onion, jalapeño (seeds out for less heat), and cilantro.",
      "Mix everything with generous lime juice and salt.",
      "Let sit 10 min for flavors to merge. Taste and adjust salt and lime.",
    ],
    gremlin_note: "White onion only. Yellow onion is too sweet; red is too sharp. And drain those tomatoes.",
    cuisine: "Mexican", level: "Beginner", servings: 4, calories: 40,
  },
  {
    name: "Tamales",
    emoji: "🫔",
    description: "Masa dough stuffed with spiced chicken and steamed in corn husks. Festive and deeply satisfying.",
    time: 120, difficulty: "Hard",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["masa harina", "chicken", "dried chiles"],
    extra_ingredients: ["lard or vegetable shortening", "chicken broth", "corn husks", "cumin", "garlic", "salt"],
    steps: [
      "Soak corn husks in warm water 30 min. Blend soaked chiles with garlic and cumin into a paste. Cook paste in oil 3 min, add shredded chicken.",
      "Beat lard or shortening until fluffy. Mix in masa harina and warm broth until the dough is soft and spreadable.",
      "Spread masa on husks, add chicken filling, fold and tie. Stand upright in a steamer.",
      "Steam for 60–75 min until masa pulls cleanly from the husk.",
    ],
    gremlin_note: "Test doneness by pulling a husk — if masa sticks, steam longer. Patience is the ingredient tamales need most.",
    cuisine: "Mexican", level: "Pro", servings: 12, calories: 360,
  },
  {
    name: "Flan",
    emoji: "🍮",
    description: "Silky Mexican custard with a bitter caramel top. Jiggling perfection that unmolds dramatically.",
    time: 60, difficulty: "Medium",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["eggs", "condensed milk", "cream", "sugar"],
    extra_ingredients: ["vanilla", "water"],
    steps: [
      "Make caramel: cook sugar and water until deep amber. Pour immediately into a loaf pan and swirl to coat.",
      "Blend eggs, condensed milk, cream, and vanilla until smooth. Strain through a sieve.",
      "Pour custard over caramel. Place pan in a water bath and bake at 160°C for 45–50 min until just set.",
      "Cool completely, then refrigerate overnight. Unmold onto a plate — the caramel cascades over the top.",
    ],
    gremlin_note: "It must be cold before unmolding. Warm flan breaks. Overnight in the fridge is not optional.",
    cuisine: "Mexican", level: "Intermediate", servings: 8, calories: 320,
  },
  {
    name: "Sopa de Lima",
    emoji: "🍋",
    description: "Bright Yucatán lime soup with chicken, tomatoes, and crispy tortilla strips.",
    time: 40, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "lime", "tomatoes", "onion"],
    extra_ingredients: ["garlic", "jalapeño", "cilantro", "chicken broth", "corn tortillas", "oil"],
    steps: [
      "Sauté onion, tomatoes, jalapeño, and garlic until soft. Add chicken broth and bring to a boil.",
      "Add chicken breasts whole, poach 15 min until cooked. Remove and shred.",
      "Add lime juice to broth — be generous. Return chicken. Simmer 5 min.",
      "Fry thin tortilla strips in oil until crispy. Serve soup topped with tortilla strips and cilantro.",
    ],
    gremlin_note: "This soup NEEDS lime — keep adding until it makes you flinch slightly. Then add a little more.",
    cuisine: "Mexican", level: "Beginner", servings: 4, calories: 280,
  },
  {
    name: "Chiles Rellenos",
    emoji: "🫑",
    description: "Roasted poblano peppers stuffed with cheese, dipped in egg batter, and fried until golden.",
    time: 45, difficulty: "Hard",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["poblano peppers", "cheese", "eggs"],
    extra_ingredients: ["tomatoes", "onion", "garlic", "cumin", "flour", "oil"],
    steps: [
      "Char poblanos directly on a flame until blackened all over. Place in a bag 10 min, then peel, making a slit to remove seeds.",
      "Stuff with cheese (Oaxacan or mozzarella). Close with a toothpick.",
      "Separate eggs. Beat whites to stiff peaks, fold in yolks and flour to make a light batter.",
      "Coat peppers in batter and fry in hot oil until golden on all sides. Serve in a tomato-onion sauce.",
    ],
    gremlin_note: "Char the poblanos completely — the blackened skin peels off and leaves a smoky roasted pepper underneath.",
    cuisine: "Mexican", level: "Pro", servings: 4, calories: 420,
  },
  {
    name: "Huevos Rancheros",
    emoji: "🍳",
    description: "Fried eggs on warm tortillas smothered in fire-roasted salsa. The Mexican breakfast that wins every morning.",
    time: 20, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["eggs", "tomatoes", "corn tortillas", "jalapeño"],
    extra_ingredients: ["onion", "garlic", "cumin", "refried beans", "avocado", "cilantro", "oil"],
    steps: [
      "Char tomatoes, jalapeño, and onion directly on flame or under broiler. Blend with garlic and cumin into a rough salsa. Simmer in oil 5 min.",
      "Warm corn tortillas in a dry pan. Spread with warmed refried beans.",
      "Fry eggs sunny-side up in a little oil.",
      "Layer: tortilla, beans, egg, salsa. Top with avocado and cilantro.",
    ],
    gremlin_note: "Char the vegetables — roasted salsa is a different animal from raw blended salsa.",
    cuisine: "Mexican", level: "Beginner", servings: 2, calories: 380,
  },

  // ── INDIAN ────────────────────────────────────────────────────────────────

  {
    name: "Butter Chicken",
    emoji: "🍛",
    description: "Tender chicken in a velvety tomato-butter-cream sauce. The dish that made Indian food go global.",
    time: 45, difficulty: "Medium",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["chicken", "tomatoes", "butter", "cream"],
    extra_ingredients: ["garlic", "ginger", "garam masala", "cumin", "kashmiri chili", "yogurt", "cashews"],
    steps: [
      "Marinate chicken in yogurt, kashmiri chili, garlic, and ginger for 30 min. Grill or pan-fry until charred.",
      "Sauté onions until golden. Add garlic, ginger paste, and spices. Cook 2 min.",
      "Add blended tomatoes and cook until oil separates from the sauce, about 15 min.",
      "Stir in butter, cream, and chicken. Simmer 10 min. Finish with a pinch of garam masala.",
    ],
    gremlin_note: "The sauce is done when oil pools on the surface — that's how you know the tomatoes have cooked through.",
    cuisine: "Indian", level: "Intermediate", servings: 4, calories: 480,
  },
  {
    name: "Palak Paneer",
    emoji: "🥬",
    description: "Fresh paneer cubes in a velvety spiced spinach sauce. Vegetarian Indian food at its best.",
    time: 35, difficulty: "Medium",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["spinach", "paneer", "onion", "tomatoes"],
    extra_ingredients: ["garlic", "ginger", "cumin", "coriander", "cream", "garam masala", "butter"],
    steps: [
      "Blanch spinach in boiling water 2 min, drain, and blend into a smooth purée.",
      "Fry paneer cubes in butter until golden on all sides. Remove.",
      "In same pan, sauté onion until soft. Add garlic, ginger, cumin, coriander, and tomatoes. Cook until oil separates.",
      "Add spinach purée, simmer 5 min. Stir in cream and paneer. Season and add garam masala.",
    ],
    gremlin_note: "Blanch and blend the spinach while it's still hot — the bright green colour holds better than if you let it cool.",
    cuisine: "Indian", level: "Intermediate", servings: 4, calories: 380,
  },
  {
    name: "Chicken Biryani",
    emoji: "🍚",
    description: "Fragrant saffron rice layered with spiced chicken and sealed to steam together. India's crown jewel.",
    time: 75, difficulty: "Hard",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["chicken", "basmati rice", "onion", "yogurt"],
    extra_ingredients: ["saffron", "ghee", "garam masala", "mint", "coriander", "whole spices", "fried onions"],
    steps: [
      "Marinate chicken in yogurt, garam masala, ginger-garlic paste, and half the fried onions. Marinate 30 min.",
      "Parboil basmati rice until 70% cooked. Drain.",
      "Layer in a heavy pot: chicken on the bottom, then rice, then saffron milk, fried onions, mint, and ghee. Seal tightly with a lid (or foil).",
      "Cook on high heat 3 min to generate steam, then on lowest heat 25 min (dum). Rest 10 min before opening.",
    ],
    gremlin_note: "The dum (sealed steam) is where biryani becomes biryani. Don't peek. A broken seal means dry rice.",
    cuisine: "Indian", level: "Pro", servings: 4, calories: 560,
  },
  {
    name: "Dal Tadka",
    emoji: "🫘",
    description: "Yellow lentils cooked until silky, finished with a sizzling spiced butter poured right at the table.",
    time: 35, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["red lentils", "tomatoes", "onion", "garlic"],
    extra_ingredients: ["cumin seeds", "mustard seeds", "turmeric", "coriander", "ghee or oil", "chili"],
    steps: [
      "Rinse lentils and simmer with turmeric, salt, and 3 cups water for 20–25 min until completely soft. Mash partially.",
      "In a separate pan (the tadka), heat ghee until smoking. Add cumin seeds, mustard seeds, dried chili — let them splutter.",
      "Add garlic and onion, cook until golden. Add tomatoes and coriander, cook 5 min.",
      "Pour the sizzling tadka directly into the lentils. Stir and serve with rice or flatbread.",
    ],
    gremlin_note: "The tadka goes in last, sizzling hot, for maximum aroma. Pre-mixing it defeats the whole point.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 280,
  },
  {
    name: "Chana Masala",
    emoji: "🫘",
    description: "Bold, tangy chickpea curry with a deeply spiced tomato-onion gravy. The weeknight legend.",
    time: 30, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chickpeas", "tomatoes", "onion", "garlic"],
    extra_ingredients: ["ginger", "cumin", "coriander", "garam masala", "amchur", "chili", "oil"],
    steps: [
      "Sauté finely chopped onion in oil until golden and slightly caramelized.",
      "Add garlic, ginger, cumin, and coriander. Fry 1 min. Add blended tomatoes and cook until oil separates.",
      "Add drained chickpeas and 200ml water. Simmer 15 min until sauce thickens and coats the chickpeas.",
      "Finish with garam masala and amchur (or lemon juice). The sourness is what makes this dish.",
    ],
    gremlin_note: "Golden onions take time. If you're not cooking them 10+ minutes, the base won't have depth.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 300,
  },
  {
    name: "Samosas",
    emoji: "🥟",
    description: "Crispy fried pastry filled with spiced potatoes and peas. India's greatest snack.",
    time: 60, difficulty: "Hard",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["flour", "potatoes", "peas", "onion"],
    extra_ingredients: ["cumin seeds", "coriander", "garam masala", "ginger", "chili", "oil for frying"],
    steps: [
      "Make dough: rub oil into flour until crumbly. Add water gradually to form a stiff dough. Rest 30 min.",
      "Boil and mash potatoes coarsely. Cook with cumin, coriander, peas, ginger, and chili until fragrant.",
      "Divide dough into balls, roll into circles, cut in half, shape into cones. Fill with potato mixture, seal edges firmly.",
      "Deep fry at 160°C (low-ish) for 5–6 min until golden and crispy. High heat makes pale, blotchy samosas.",
    ],
    gremlin_note: "160°C — lower than you think. High heat makes the outside brown before the pastry cooks through properly.",
    cuisine: "Indian", level: "Pro", servings: 12, calories: 280,
  },
  {
    name: "Garlic Naan",
    emoji: "🫓",
    description: "Pillowy, slightly charred flatbread slicked with garlic butter. No tandoor needed.",
    time: 45, difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["flour", "yogurt", "garlic"],
    extra_ingredients: ["yeast", "sugar", "salt", "butter", "milk", "coriander"],
    steps: [
      "Mix flour, yeast, sugar, and salt. Add yogurt and milk, knead 8 min until smooth. Rest 1 hour until doubled.",
      "Divide into balls. Flatten each, press garlic into the surface, roll into a teardrop shape.",
      "Cook in a very hot dry pan — as hot as it goes — until bubbles form and base chars in spots, 2 min. Flip 30 seconds.",
      "Brush immediately with garlic butter and fresh coriander.",
    ],
    gremlin_note: "The pan must be screaming hot. A medium-heat naan is pale, flat, and sad.",
    cuisine: "Indian", level: "Intermediate", servings: 6, calories: 260,
  },
  {
    name: "Aloo Gobi",
    emoji: "🥔",
    description: "Potato and cauliflower dry-fried with turmeric and cumin. Simple, golden, and deeply good.",
    time: 30, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["potatoes", "cauliflower", "onion", "tomatoes"],
    extra_ingredients: ["cumin seeds", "turmeric", "coriander", "ginger", "garlic", "garam masala", "oil"],
    steps: [
      "Heat oil, add cumin seeds and let them splutter. Add garlic and ginger, fry 1 min.",
      "Add diced potatoes and cauliflower. Coat in turmeric and coriander. Cook on medium-high without stirring too often — you want color.",
      "Add tomatoes and a splash of water, cover and cook 10–12 min until vegetables are tender.",
      "Uncover, stir, add garam masala. Fry off any remaining water until the dish looks dry and slightly golden.",
    ],
    gremlin_note: "Aloo gobi should be DRY. If there's liquid in the pan, turn up the heat and cook it off.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 220,
  },
  {
    name: "Lamb Rogan Josh",
    emoji: "🍖",
    description: "Aromatic Kashmiri lamb curry with whole spices and a deep brick-red gravy.",
    time: 75, difficulty: "Medium",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["lamb", "tomatoes", "onion", "yogurt"],
    extra_ingredients: ["garlic", "ginger", "kashmiri chili", "garam masala", "whole spices", "ghee"],
    steps: [
      "In ghee, bloom whole spices (cardamom, cloves, cinnamon, bay). Add onion until deep golden.",
      "Add garlic-ginger paste and kashmiri chili powder. Fry 2 min until fragrant.",
      "Add lamb chunks, brown on all sides. Add beaten yogurt a spoonful at a time, stirring after each.",
      "Add tomatoes, water to cover, and simmer covered 45–50 min until lamb is very tender. Finish with garam masala.",
    ],
    gremlin_note: "Add the yogurt slowly and keep stirring — dumping it all in at once makes it split and curdle.",
    cuisine: "Indian", level: "Intermediate", servings: 4, calories: 520,
  },
  {
    name: "Paneer Tikka Masala",
    emoji: "🧀",
    description: "Grilled paneer cubes in a smoky, creamy orange tomato sauce. A vegetarian showstopper.",
    time: 40, difficulty: "Medium",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["paneer", "tomatoes", "cream", "onion"],
    extra_ingredients: ["garlic", "ginger", "tikka spices", "yogurt", "butter", "kashmiri chili", "garam masala"],
    steps: [
      "Marinate paneer cubes in yogurt, tikka spices, garlic, and ginger. Grill or pan-fry until charred on edges.",
      "Sauté onion until golden. Add garlic, ginger, and kashmiri chili. Fry 2 min.",
      "Add blended tomatoes and cook until oil separates. Add cream and butter.",
      "Add paneer and simmer 5 min. Finish with garam masala.",
    ],
    gremlin_note: "Char the paneer before adding to sauce. Pale paneer floating in sauce is texturally boring.",
    cuisine: "Indian", level: "Intermediate", servings: 4, calories: 420,
  },
  {
    name: "Masala Dosa",
    emoji: "🫓",
    description: "Crispy fermented rice crepe filled with spiced potato. South India's finest street food.",
    time: 30, difficulty: "Medium",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["dosa batter", "potatoes", "onion"],
    extra_ingredients: ["mustard seeds", "curry leaves", "turmeric", "chili", "oil", "coconut chutney"],
    steps: [
      "Boil and roughly mash potatoes. Heat oil, add mustard seeds — let them pop. Add curry leaves and chili.",
      "Add onion and cook until soft. Add turmeric and potatoes, mix well to coat. Season.",
      "Heat a flat pan on high. Add a ladle of dosa batter, spread in circles from centre outwards, thin as possible. Drizzle oil around edges.",
      "Cook until edges lift and the dosa is crispy. Add potato filling on one half and fold. Serve with chutney.",
    ],
    gremlin_note: "The pan must be very hot AND slightly oiled for the first dosa. The first one is always a test one.",
    cuisine: "Indian", level: "Intermediate", servings: 4, calories: 300,
  },
  {
    name: "Kheer",
    emoji: "🍚",
    description: "Slow-cooked rice pudding perfumed with saffron, cardamom, and rose water.",
    time: 40, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["short-grain rice", "milk", "sugar", "cardamom"],
    extra_ingredients: ["saffron", "rose water", "almonds", "pistachios"],
    steps: [
      "Rinse rice, then simmer in full-fat milk on low heat, stirring frequently, for 25–30 min until thick and creamy.",
      "Add sugar and saffron milk, stir well, cook 5 more min.",
      "Remove from heat, stir in rose water and cardamom.",
      "Serve warm or chilled, topped with sliced almonds and pistachios.",
    ],
    gremlin_note: "Stir constantly — milk sticks and burns on the bottom in an instant. This is a recipe you stand over.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 280,
  },
  {
    name: "Mango Lassi",
    emoji: "🥭",
    description: "Cold, thick mango and yogurt drink with cardamom. The ideal counterbalance to any spicy curry.",
    time: 5, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["mango", "yogurt", "milk"],
    extra_ingredients: ["sugar", "cardamom", "ice", "rose water"],
    steps: [
      "Peel and dice ripe mango (or use canned alphonso mango pulp).",
      "Blend mango, yogurt, and milk until completely smooth.",
      "Add sugar, cardamom, and a splash of rose water. Blend again.",
      "Pour over ice and drink immediately.",
    ],
    gremlin_note: "Alphonso mango pulp from a can makes a better lassi than most fresh mangoes you'll find outside of season.",
    cuisine: "Indian", level: "Beginner", servings: 2, calories: 220,
  },
  {
    name: "Saag Aloo",
    emoji: "🥬",
    description: "Hearty spinach and potato curry — earthy, warmly spiced, and honestly better the next day.",
    time: 30, difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["spinach", "potatoes", "onion", "garlic"],
    extra_ingredients: ["ginger", "cumin", "turmeric", "coriander", "oil", "chili"],
    steps: [
      "Parboil diced potatoes until almost tender, drain.",
      "Heat oil, add cumin and let it splutter. Add onion until golden.",
      "Add garlic, ginger, turmeric, coriander, and chili. Fry 1 min. Add potatoes and coat in spices.",
      "Add fresh spinach in batches, stirring until wilted. Cook 5 min. Season well.",
    ],
    gremlin_note: "Add spinach in batches — the whole bag at once creates steam and makes the potatoes soggy.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 240,
  },
  {
    name: "Raita",
    emoji: "🥒",
    description: "Cool, herbed yogurt with cucumber. The essential cooling agent for any spicy Indian meal.",
    time: 10, difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["yogurt", "cucumber", "mint"],
    extra_ingredients: ["cumin", "salt", "coriander", "chili", "sugar"],
    steps: [
      "Grate or finely dice cucumber. Salt it, rest 5 min, then squeeze out excess water.",
      "Whisk yogurt until smooth. Fold in cucumber, chopped mint, and coriander.",
      "Season with roasted cumin powder, salt, and a pinch of sugar.",
      "Chill until serving. Drizzle a little chili oil on top if desired.",
    ],
    gremlin_note: "Squeeze the cucumber dry or you'll have watery raita that runs all over the plate.",
    cuisine: "Indian", level: "Beginner", servings: 4, calories: 80,
  },

  // ── THAI ──────────────────────────────────────────────────────────────────

  {
    name: "Pad Thai",
    emoji: "🍜",
    description: "Wok-fried rice noodles with shrimp, egg, bean sprouts, and tamarind. Thailand's national dish.",
    time: 20, difficulty: "Medium",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["rice noodles", "shrimp", "eggs", "bean sprouts"],
    extra_ingredients: ["fish sauce", "tamarind paste", "sugar", "peanuts", "lime", "green onion", "oil"],
    steps: [
      "Soak rice noodles in cold water 30 min, drain. Make sauce: mix fish sauce, tamarind paste, and sugar.",
      "Stir-fry shrimp in very hot oil until just pink. Push to side, add noodles.",
      "Add sauce and toss. Push to side, scramble eggs in the pan, mix through.",
      "Toss in bean sprouts for 30 seconds (keep them crunchy). Plate and top with peanuts, green onion, and lime.",
    ],
    gremlin_note: "Very hot wok, small batches. Pad Thai for a crowd loses all texture. Make one portion at a time.",
    cuisine: "Thai", level: "Intermediate", servings: 2, calories: 520,
  },
  {
    name: "Thai Green Curry",
    emoji: "🍛",
    description: "Fragrant coconut curry with green chile heat, Thai basil, and crisp vegetables.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["green curry paste", "coconut milk", "chicken", "vegetables"],
    extra_ingredients: ["fish sauce", "palm sugar", "Thai basil", "kaffir lime leaves", "bamboo shoots", "oil"],
    steps: [
      "Fry green curry paste in oil until fragrant, about 2 min.",
      "Add the thick cream from the top of the coconut can, cook until it splits and looks oily.",
      "Add chicken and coat in paste. Pour in remaining coconut milk, bamboo shoots, and kaffir lime leaves.",
      "Simmer 10–12 min. Season with fish sauce and palm sugar. Finish with Thai basil.",
    ],
    gremlin_note: "Cook the paste before adding liquid — it needs to toast in oil to release its aromatics.",
    cuisine: "Thai", level: "Beginner", servings: 4, calories: 440,
  },
  {
    name: "Tom Yum Soup",
    emoji: "🍲",
    description: "Hot and sour Thai soup with shrimp, lemongrass, and galangal. Explosive flavor in every spoonful.",
    time: 25, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["shrimp", "lemongrass", "kaffir lime leaves", "galangal"],
    extra_ingredients: ["fish sauce", "lime juice", "chili", "mushrooms", "tomatoes", "cilantro"],
    steps: [
      "Simmer lemongrass (bruised), galangal slices, and kaffir lime leaves in water or stock for 10 min.",
      "Add mushrooms and tomatoes, simmer 3 min.",
      "Add shrimp and cook until pink, 2 min.",
      "Season with fish sauce, lime juice, and chili. Taste — it should be sharp, sour, and spicy in equal measure. Garnish with cilantro.",
    ],
    gremlin_note: "The lemongrass, galangal, and lime leaves are aromatics only — warn guests not to eat them.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 180,
  },
  {
    name: "Massaman Curry",
    emoji: "🍛",
    description: "Slow-braised beef in a mild, nutty curry with potatoes and peanuts. Thai-Persian fusion perfection.",
    time: 60, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["beef", "coconut milk", "potatoes", "peanuts"],
    extra_ingredients: ["massaman curry paste", "fish sauce", "palm sugar", "tamarind", "onion", "cardamom", "cinnamon"],
    steps: [
      "Fry massaman paste in thick coconut cream 3 min until fragrant.",
      "Add beef chunks and coat. Add remaining coconut milk, potatoes, onion, peanuts, cardamom, and cinnamon.",
      "Simmer covered 40–45 min until beef is very tender.",
      "Season with fish sauce, palm sugar, and tamarind until the balance of sweet, sour, and salty is right.",
    ],
    gremlin_note: "Massaman is the mildest Thai curry — it's about depth and complexity, not heat. Don't rush the simmer.",
    cuisine: "Thai", level: "Intermediate", servings: 4, calories: 560,
  },
  {
    name: "Pad See Ew",
    emoji: "🍜",
    description: "Wide rice noodles wok-fried in dark soy sauce with chicken, egg, and Chinese broccoli.",
    time: 20, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["wide rice noodles", "chicken", "Chinese broccoli", "eggs"],
    extra_ingredients: ["soy sauce", "oyster sauce", "dark soy sauce", "sugar", "oil"],
    steps: [
      "Soak wide noodles in cold water until pliable, drain.",
      "Stir-fry chicken in very hot oil until cooked. Remove.",
      "Add noodles to the wok, resist stirring — let them get some char. Add dark soy, soy, oyster sauce, and sugar. Toss.",
      "Push to side, crack in eggs, scramble lightly, then mix through with broccoli until just wilted. Return chicken.",
    ],
    gremlin_note: "Let the noodles sit on the hot wok without stirring for 30 seconds. That char is the whole point.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 480,
  },
  {
    name: "Som Tum",
    emoji: "🥗",
    description: "Green papaya salad pounded with lime, fish sauce, and chili. Crunchy, bright, and dangerously addictive.",
    time: 15, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["green papaya", "tomatoes", "green beans", "peanuts"],
    extra_ingredients: ["fish sauce", "lime juice", "palm sugar", "garlic", "dried shrimp", "chili"],
    steps: [
      "Shred green papaya into thin matchsticks using a grater or peeler.",
      "In a mortar, pound garlic and chili into a rough paste.",
      "Add tomatoes and green beans, pound lightly — break, not mush.",
      "Add papaya, fish sauce, lime juice, and sugar. Mix and pound gently. Top with peanuts.",
    ],
    gremlin_note: "The balance is hot, sour, salty, and slightly sweet — all four at once. Keep tasting and adjusting.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 140,
  },
  {
    name: "Thai Fried Rice",
    emoji: "🍚",
    description: "Jasmine rice stir-fried with chicken, egg, and soy sauce. Proof that leftovers make the best food.",
    time: 15, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["jasmine rice", "chicken", "eggs", "onion"],
    extra_ingredients: ["soy sauce", "fish sauce", "garlic", "tomato", "cucumber", "lime", "oil"],
    steps: [
      "Use day-old cold rice — freshly cooked rice is too wet and clumps in the wok.",
      "Stir-fry chicken in very hot oil until cooked. Add garlic and onion.",
      "Add rice and break up any clumps. Stir-fry on high heat, letting it crackle.",
      "Season with soy sauce and fish sauce. Push to side, scramble an egg in, mix through. Serve with cucumber and lime.",
    ],
    gremlin_note: "Day-old fridge rice only. If you must use fresh rice, spread it on a tray and refrigerate 2 hours.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 420,
  },
  {
    name: "Chicken Satay",
    emoji: "🍢",
    description: "Grilled marinated chicken skewers with an irresistible peanut dipping sauce.",
    time: 30, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "peanut butter", "coconut milk", "lemongrass"],
    extra_ingredients: ["turmeric", "coriander", "cumin", "soy sauce", "lime", "sugar", "chili", "skewers"],
    steps: [
      "Blend lemongrass, turmeric, coriander, cumin, soy sauce, and coconut milk into a marinade. Coat chicken strips and rest 30 min.",
      "Thread onto skewers and grill over high heat, 3–4 min per side.",
      "Peanut sauce: heat peanut butter, coconut milk, soy sauce, lime, sugar, and chili until smooth. Add water to thin.",
      "Serve skewers with peanut sauce for dipping.",
    ],
    gremlin_note: "Press the chicken flat on the skewer so it cooks evenly — a thick lump burns outside before cooking inside.",
    cuisine: "Thai", level: "Beginner", servings: 4, calories: 380,
  },
  {
    name: "Thai Red Curry",
    emoji: "🍛",
    description: "Bolder and spicier than green curry — coconut milk with red chile heat and Thai basil.",
    time: 25, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["red curry paste", "coconut milk", "chicken", "bamboo shoots"],
    extra_ingredients: ["fish sauce", "palm sugar", "Thai basil", "kaffir lime leaves", "oil"],
    steps: [
      "Fry red curry paste in oil 2 min until fragrant and slightly darker.",
      "Add thick coconut cream from top of can, stir until splits and looks oily.",
      "Add chicken, bamboo shoots, and remaining coconut milk. Simmer 12 min.",
      "Season with fish sauce and palm sugar. Finish with kaffir lime leaves and Thai basil.",
    ],
    gremlin_note: "If the coconut milk doesn't split and look oily when you fry it, you haven't cooked it long enough.",
    cuisine: "Thai", level: "Beginner", servings: 4, calories: 420,
  },
  {
    name: "Tom Kha Gai",
    emoji: "🍲",
    description: "Coconut milk soup with chicken, galangal, and lemongrass. Silky, fragrant, and deeply soothing.",
    time: 25, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "coconut milk", "galangal", "lemongrass"],
    extra_ingredients: ["kaffir lime leaves", "fish sauce", "lime juice", "mushrooms", "chili", "cilantro"],
    steps: [
      "Simmer coconut milk with bruised lemongrass, galangal, and kaffir lime leaves for 10 min.",
      "Add sliced chicken and mushrooms. Cook 8 min.",
      "Season with fish sauce and lime juice. Add chili.",
      "Taste — it should be rich, sour, and gently spiced. Top with cilantro.",
    ],
    gremlin_note: "Don't let coconut milk boil hard — it breaks into greasy pools. Gentle simmer throughout.",
    cuisine: "Thai", level: "Beginner", servings: 4, calories: 340,
  },
  {
    name: "Larb",
    emoji: "🥗",
    description: "Ground chicken salad with shallots, mint, lime, and toasted rice powder. Northeast Thailand on a plate.",
    time: 20, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["ground chicken", "shallots", "mint", "lime"],
    extra_ingredients: ["fish sauce", "toasted rice powder", "chili flakes", "cilantro", "lemongrass"],
    steps: [
      "Toast rice in a dry pan until golden and nutty. Grind to a coarse powder.",
      "Cook ground chicken in a dry pan until just cooked through. Cool slightly.",
      "Mix chicken with shallots, fresh mint, cilantro, and lemongrass.",
      "Dress with fish sauce, lime juice, and chili flakes. Toss. Sprinkle toasted rice powder over everything.",
    ],
    gremlin_note: "The toasted rice powder is what makes larb larb — don't skip it. It adds crunch and a nutty smokiness.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 280,
  },
  {
    name: "Mango Sticky Rice",
    emoji: "🥭",
    description: "Sweet glutinous rice in salted coconut cream with ripe mango. Thailand's most beloved dessert.",
    time: 40, difficulty: "Medium",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["glutinous rice", "mango", "coconut milk", "sugar"],
    extra_ingredients: ["salt", "sesame seeds"],
    steps: [
      "Soak glutinous rice overnight. Steam for 25–30 min until tender and translucent.",
      "Warm half the coconut milk with sugar and salt until dissolved. Pour over hot rice, cover, and let absorb 20 min.",
      "Heat remaining coconut milk with a pinch of salt for the sauce.",
      "Plate sticky rice with sliced ripe mango. Drizzle coconut sauce over and top with sesame seeds.",
    ],
    gremlin_note: "Soak the rice overnight — not optional. Unsoaked glutinous rice steams unevenly with a chalky center.",
    cuisine: "Thai", level: "Intermediate", servings: 4, calories: 380,
  },
  {
    name: "Khai Jiao",
    emoji: "🍳",
    description: "Thai deep-fried omelette — puffy, golden, crispy at the edges, served with jasmine rice.",
    time: 10, difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["eggs", "fish sauce", "onion"],
    extra_ingredients: ["oil", "white pepper", "soy sauce", "green onion", "chili", "rice"],
    steps: [
      "Beat eggs well with fish sauce, a splash of soy sauce, and white pepper.",
      "Heat a generous amount of oil in a small deep pan — more than you think. Get it very hot.",
      "Pour in egg mixture. It should puff up dramatically in the hot oil.",
      "Fry until golden and set on the bottom, flip once briefly. Drain and serve over rice with chili sauce.",
    ],
    gremlin_note: "This uses more oil than a standard omelette on purpose — the egg puffs in the hot oil. Low oil = flat egg.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 240,
  },
  {
    name: "Pad Kra Pao",
    emoji: "🌿",
    description: "Fiery stir-fried pork with Thai holy basil. The dish every Thai person craves at midnight.",
    time: 15, difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["ground pork", "Thai basil", "chili", "garlic"],
    extra_ingredients: ["oyster sauce", "fish sauce", "soy sauce", "sugar", "oil", "eggs", "rice"],
    steps: [
      "Pound garlic and chili in a mortar (or mince fine). Fry in very hot oil until fragrant.",
      "Add ground pork and break up. Stir-fry on high heat until cooked and starting to char slightly.",
      "Add oyster sauce, fish sauce, soy sauce, and a pinch of sugar. Stir-fry 1 more minute.",
      "Turn off heat, add a massive handful of Thai basil. Stir until wilted. Serve over rice with a fried egg.",
    ],
    gremlin_note: "Holy basil only if you can find it. Regular basil works but the flavor is noticeably different.",
    cuisine: "Thai", level: "Beginner", servings: 2, calories: 380,
  },
  {
    name: "Thai Fish Cakes",
    emoji: "🐟",
    description: "Bouncy, fragrant fish cakes with red curry paste and kaffir lime. Addictive street food.",
    time: 25, difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["fish", "red curry paste", "eggs", "green beans"],
    extra_ingredients: ["fish sauce", "kaffir lime leaves", "sugar", "oil for frying", "sweet chili sauce"],
    steps: [
      "Pulse fish fillets in a food processor until a smooth paste. Mix in red curry paste, egg, fish sauce, and sugar.",
      "Fold in thinly sliced kaffir lime leaves and finely sliced green beans.",
      "Shape into small round patties. The mixture will be quite sticky.",
      "Fry in shallow oil at 170°C for 2–3 min per side until deep golden. Serve with sweet chili sauce.",
    ],
    gremlin_note: "Mix the fish paste aggressively — the bouncy texture comes from working the proteins. Don't be gentle.",
    cuisine: "Thai", level: "Intermediate", servings: 4, calories: 320,
  },
];
