// Approximate per-serving macros (grams). Only populated for recipes we have data for.
export const NUTRITION: Record<string, { protein: number; carbs: number; fat: number }> = {
  // ── Italian ──────────────────────────────────────────────────────────────
  "Pasta Carbonara":          { protein: 32, carbs: 58, fat: 22 },
  "Pasta all'Amatriciana":    { protein: 26, carbs: 72, fat: 14 },
  "Saffron Risotto":          { protein: 14, carbs: 68, fat: 14 },
  "Pollo alla Cacciatore":    { protein: 38, carbs: 12, fat: 18 },
  "Pizza Margherita":         { protein: 18, carbs: 58, fat: 16 },
  "Focaccia":                 { protein:  8, carbs: 52, fat: 12 },
  "Saltimbocca":              { protein: 40, carbs:  4, fat: 22 },
  "Ribollita":                { protein: 12, carbs: 48, fat: 10 },
  "Tiramisu":                 { protein:  8, carbs: 52, fat: 28 },
  "Potato Gnocchi":           { protein: 14, carbs: 70, fat: 12 },
  "Panzanella":               { protein:  8, carbs: 42, fat: 16 },
  "Pasta e Fagioli":          { protein: 18, carbs: 62, fat:  8 },
  "Bistecca alla Fiorentina": { protein: 55, carbs:  2, fat: 32 },
  "Arancini":                 { protein: 14, carbs: 58, fat: 18 },
  "Osso Buco":                { protein: 48, carbs:  8, fat: 24 },

  // ── Moroccan ─────────────────────────────────────────────────────────────
  "Chicken Tagine":                    { protein: 42, carbs: 12, fat: 18 },
  "Lamb Tagine with Prunes":           { protein: 38, carbs: 44, fat: 26 },
  "Harira":                            { protein: 18, carbs: 38, fat:  8 },
  "Kefta Tagine":                      { protein: 36, carbs: 14, fat: 24 },
  "Zaalouk":                           { protein:  4, carbs: 16, fat: 10 },
  "Chermoula Fish":                    { protein: 36, carbs:  6, fat: 12 },
  "Couscous with Seven Vegetables":    { protein: 16, carbs: 60, fat:  8 },
  "Taktouka":                          { protein:  4, carbs: 18, fat: 10 },
  "Moroccan Carrot Salad":             { protein:  2, carbs: 22, fat:  6 },
  "Bissara":                           { protein: 14, carbs: 34, fat:  6 },
  "Rfissa":                            { protein: 38, carbs: 48, fat: 16 },
  "Bastilla":                          { protein: 28, carbs: 40, fat: 24 },
  "Moroccan Chickpea and Spinach Stew":{ protein: 14, carbs: 36, fat:  8 },
  "Mrouzia":                           { protein: 42, carbs: 28, fat: 26 },
  "Mechoui":                           { protein: 52, carbs:  2, fat: 28 },

  // ── Japanese ─────────────────────────────────────────────────────────────
  "Tonkotsu Ramen":   { protein: 28, carbs: 65, fat: 22 },
  "Karaage Chicken":  { protein: 38, carbs: 18, fat: 22 },
  "Gyoza":            { protein: 22, carbs: 28, fat: 14 },
  "Teriyaki Salmon":  { protein: 42, carbs: 24, fat: 18 },
  "Miso Soup":        { protein:  8, carbs:  8, fat:  4 },
  "Yakitori":         { protein: 32, carbs: 12, fat: 10 },
  "Okonomiyaki":      { protein: 18, carbs: 42, fat: 16 },
  "Japanese Curry":   { protein: 28, carbs: 58, fat: 18 },
  "Cold Soba Noodles":{ protein: 14, carbs: 52, fat:  4 },
  "Tamagoyaki":       { protein: 14, carbs:  4, fat: 10 },
  "Onigiri":          { protein:  8, carbs: 48, fat:  2 },
  "Korokke":          { protein: 18, carbs: 38, fat: 16 },
  "Oyakodon":         { protein: 34, carbs: 58, fat: 14 },
  "Tempura Udon":     { protein: 22, carbs: 68, fat: 14 },
  "Katsu Sando":      { protein: 36, carbs: 52, fat: 22 },

  // ── Mexican ──────────────────────────────────────────────────────────────
  "Tacos al Pastor":  { protein: 34, carbs: 32, fat: 16 },
  "Guacamole":        { protein:  2, carbs:  8, fat: 22 },
  "Chicken Enchiladas":{ protein: 38, carbs: 42, fat: 22 },
  "Carnitas":         { protein: 42, carbs:  4, fat: 28 },
  "Quesadillas":      { protein: 22, carbs: 38, fat: 18 },
  "Birria Tacos":     { protein: 38, carbs: 28, fat: 22 },
  "Elote":            { protein:  4, carbs: 28, fat: 12 },
  "Chilaquiles":      { protein: 16, carbs: 42, fat: 18 },
  "Pozole Rojo":      { protein: 32, carbs: 28, fat: 14 },
  "Pico de Gallo":    { protein:  1, carbs:  8, fat:  1 },
  "Tamales":          { protein: 14, carbs: 48, fat: 14 },
  "Flan":             { protein:  8, carbs: 42, fat: 14 },
  "Sopa de Lima":     { protein: 28, carbs: 22, fat: 10 },
  "Chiles Rellenos":  { protein: 18, carbs: 22, fat: 18 },
  "Huevos Rancheros": { protein: 18, carbs: 28, fat: 14 },

  // ── Indian ───────────────────────────────────────────────────────────────
  "Butter Chicken":       { protein: 38, carbs: 18, fat: 26 },
  "Palak Paneer":         { protein: 22, carbs: 12, fat: 22 },
  "Chicken Biryani":      { protein: 42, carbs: 68, fat: 22 },
  "Dal Tadka":            { protein: 18, carbs: 42, fat: 10 },
  "Chana Masala":         { protein: 14, carbs: 38, fat: 10 },
  "Samosas":              { protein:  8, carbs: 32, fat: 14 },
  "Garlic Naan":          { protein:  8, carbs: 42, fat:  8 },
  "Aloo Gobi":            { protein:  6, carbs: 28, fat:  8 },
  "Lamb Rogan Josh":      { protein: 42, carbs: 10, fat: 28 },
  "Paneer Tikka Masala":  { protein: 24, carbs: 16, fat: 26 },
  "Masala Dosa":          { protein:  8, carbs: 52, fat:  8 },
  "Kheer":                { protein:  6, carbs: 42, fat: 12 },
  "Mango Lassi":          { protein:  4, carbs: 38, fat:  4 },
  "Saag Aloo":            { protein:  6, carbs: 28, fat: 12 },
  "Raita":                { protein:  4, carbs:  8, fat:  4 },

  // ── Thai ─────────────────────────────────────────────────────────────────
  "Pad Thai":         { protein: 22, carbs: 58, fat: 14 },
  "Thai Green Curry": { protein: 32, carbs: 18, fat: 28 },
  "Tom Yum Soup":     { protein: 18, carbs: 10, fat:  6 },
  "Massaman Curry":   { protein: 28, carbs: 42, fat: 24 },
  "Pad See Ew":       { protein: 22, carbs: 58, fat: 14 },
  "Som Tum":          { protein:  4, carbs: 14, fat:  2 },
  "Thai Fried Rice":  { protein: 18, carbs: 62, fat: 12 },
  "Chicken Satay":    { protein: 34, carbs: 12, fat: 16 },
  "Thai Red Curry":   { protein: 28, carbs: 16, fat: 26 },
  "Tom Kha Gai":      { protein: 24, carbs:  8, fat: 18 },
  "Larb":             { protein: 28, carbs:  8, fat: 14 },
  "Mango Sticky Rice":{ protein:  4, carbs: 68, fat:  8 },
  "Khai Jiao":        { protein: 16, carbs:  4, fat: 22 },
  "Pad Kra Pao":      { protein: 32, carbs:  8, fat: 16 },
  "Thai Fish Cakes":  { protein: 24, carbs: 16, fat: 12 },

  // ── Popular general ───────────────────────────────────────────────────────
  "Spaghetti Bolognese":   { protein: 38, carbs: 68, fat: 18 },
  "Pasta Aglio e Olio":    { protein: 12, carbs: 72, fat: 18 },
  "Chicken Stir Fry":      { protein: 42, carbs: 38, fat: 14 },
  "Vegetable Curry":       { protein: 12, carbs: 48, fat: 16 },
  "Omelette":              { protein: 18, carbs:  4, fat: 16 },
  "Grilled Salmon":        { protein: 46, carbs:  2, fat: 22 },
  "Caesar Salad":          { protein: 16, carbs: 18, fat: 24 },
  "Beef Tacos":            { protein: 32, carbs: 38, fat: 22 },
  "Mushroom Risotto":      { protein: 12, carbs: 68, fat: 16 },
  "French Toast":          { protein: 14, carbs: 52, fat: 18 },
  "Shakshuka":             { protein: 18, carbs: 22, fat: 16 },
  "Chicken Tikka Masala":  { protein: 38, carbs: 24, fat: 22 },
  "Fried Rice":            { protein: 16, carbs: 62, fat: 14 },
  "Avocado Toast":         { protein: 10, carbs: 32, fat: 18 },
  "Grilled Cheese":        { protein: 14, carbs: 28, fat: 22 },
  "Lentil Soup":           { protein: 18, carbs: 42, fat:  6 },
  "Pancakes":              { protein: 10, carbs: 58, fat: 14 },
  "Banana Bread":          { protein:  8, carbs: 62, fat: 18 },
};
