export interface Recipe {
  name: string;
  emoji: string;
  description: string;
  time: number;
  difficulty: "Easy" | "Medium" | "Hard";
  dietary: string[];
  key_ingredients: string[];
  extra_ingredients: string[];
  steps: string[];
  gremlin_note: string;
  cuisine?: string;
  level?: "Beginner" | "Intermediate" | "Pro";
  servings?: number;
  calories?: number;
}

export interface ResolvedRecipe {
  name: string;
  emoji: string;
  description: string;
  time: string;
  difficulty: string;
  matched_ingredients: string[];
  extra_ingredients: string[];
  steps: string[];
  gremlin_note: string;
  cuisine?: string;
  level?: string;
  servings?: number;
  calories?: number;
}

export const RECIPES: Recipe[] = [
  // ── PASTA ──
  {
    name: "Spaghetti Bolognese",
    emoji: "🍝",
    description: "A hearty meat sauce clinging to every strand of pasta. The classic you always come back to.",
    time: 35,
    difficulty: "Medium",
    dietary: ["halal"],
    key_ingredients: ["pasta", "beef", "tomatoes"],
    extra_ingredients: ["onion", "garlic", "olive oil", "salt", "pepper"],
    steps: [
      "Brown the ground beef in a pan over medium-high heat. Drain excess fat.",
      "Add diced onion and garlic, cook 2 minutes until soft.",
      "Stir in crushed tomatoes, salt, and pepper. Simmer 20 minutes.",
      "Cook pasta per package instructions. Drain.",
      "Toss pasta with sauce and serve hot.",
    ],
    gremlin_note: "Don't drain all the pasta water — a splash in the sauce makes it silky. Trust the gremlin.",
  },
  {
    name: "Pasta Aglio e Olio",
    emoji: "🧄",
    description: "Four ingredients, ten minutes, and you'll feel like an Italian grandma.",
    time: 15,
    difficulty: "Easy",
    dietary: ["vegetarian", "vegan", "dairy-free", "halal"],
    key_ingredients: ["pasta", "garlic"],
    extra_ingredients: ["olive oil", "chili flakes", "salt", "parsley"],
    steps: [
      "Cook pasta in heavily salted boiling water. Reserve 1 cup pasta water before draining.",
      "Slice garlic thinly. Warm olive oil in a pan over low heat, add garlic until golden.",
      "Add chili flakes, then the drained pasta and a splash of pasta water.",
      "Toss vigorously until sauce coats the pasta. Serve immediately.",
    ],
    gremlin_note: "The golden garlic is sacred. Burn it and start over. No compromises.",
  },
  {
    name: "Mac and Cheese",
    emoji: "🧀",
    description: "Creamy, gooey, aggressively cheesy. Comfort in a bowl.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["pasta", "cheese", "milk"],
    extra_ingredients: ["butter", "flour", "salt", "pepper"],
    steps: [
      "Cook pasta until al dente. Drain and set aside.",
      "Melt butter in the same pot, whisk in flour to make a roux.",
      "Gradually add milk, whisking constantly until thickened.",
      "Remove from heat, stir in cheese until melted.",
      "Add pasta back, stir to coat. Season with salt and pepper.",
    ],
    gremlin_note: "Use whatever cheese you have. Mix them. The weirder the combo the better it tastes.",
  },
  {
    name: "Pesto Pasta",
    emoji: "🌿",
    description: "Bright, herby, and ready in the time it takes pasta to cook.",
    time: 15,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["pasta", "basil", "garlic", "parmesan"],
    extra_ingredients: ["olive oil", "pine nuts", "salt", "lemon"],
    steps: [
      "Cook pasta in salted boiling water. Reserve some pasta water.",
      "Blend basil, garlic, parmesan, pine nuts, and olive oil until smooth.",
      "Toss drained pasta with pesto, adding pasta water to loosen.",
      "Taste, season, and serve.",
    ],
    gremlin_note: "No pine nuts? Walnuts, cashews, or nothing. Pesto forgives.",
  },
  {
    name: "Arrabbiata Pasta",
    emoji: "🌶️",
    description: "Angry tomato sauce. Spicy, garlicky, deliciously aggressive.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian", "vegan", "dairy-free", "halal"],
    key_ingredients: ["pasta", "tomatoes", "garlic"],
    extra_ingredients: ["olive oil", "chili flakes", "salt"],
    steps: [
      "Cook pasta in salted boiling water. Drain and set aside.",
      "Heat olive oil, add sliced garlic and chili flakes until fragrant.",
      "Add crushed tomatoes, salt. Simmer 15 minutes.",
      "Toss pasta in sauce. Serve hot.",
    ],
    gremlin_note: "Add more chili than you think. That's the whole point of this dish.",
  },
  {
    name: "Tuna Pasta",
    emoji: "🐟",
    description: "A pantry hero. Tuna, pasta, done — better than it has any right to be.",
    time: 15,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["pasta", "tuna", "tomatoes"],
    extra_ingredients: ["garlic", "olive oil", "capers", "salt", "pepper"],
    steps: [
      "Cook pasta in salted boiling water. Drain.",
      "Warm olive oil in a pan, add garlic until golden.",
      "Add crushed tomatoes, simmer 5 minutes.",
      "Stir in drained tuna, capers, salt and pepper.",
      "Toss with pasta and serve.",
    ],
    gremlin_note: "Canned tuna is an underrated king. Don't let anyone tell you otherwise.",
  },
  {
    name: "Pasta Primavera",
    emoji: "🥦",
    description: "Pasta with whatever vegetables you have. Spring on a plate.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["pasta", "vegetables", "garlic"],
    extra_ingredients: ["olive oil", "parmesan", "salt", "pepper", "lemon"],
    steps: [
      "Cook pasta in salted boiling water. Reserve pasta water. Drain.",
      "Sauté garlic in olive oil, add chopped vegetables and cook until tender.",
      "Toss pasta with vegetables, a splash of pasta water, and olive oil.",
      "Finish with parmesan, lemon zest, salt and pepper.",
    ],
    gremlin_note: "Use any vegetables. The goal is to use what's dying in the fridge. This is the recipe for that.",
  },
  {
    name: "Cacio e Pepe",
    emoji: "🧀",
    description: "Two ingredients (pasta water counts). Simultaneously simple and tricky. Worth it.",
    time: 15,
    difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["pasta", "parmesan", "pepper"],
    extra_ingredients: ["salt", "pasta water"],
    steps: [
      "Cook pasta in salted water. Reserve 1.5 cups pasta water before draining.",
      "Toast black pepper in a dry pan until fragrant. Add a ladle of pasta water.",
      "Add drained pasta to the pan, toss over medium heat.",
      "Remove from heat, add finely grated parmesan and a splash of pasta water.",
      "Toss vigorously until creamy. Serve immediately.",
    ],
    gremlin_note: "The pasta water is the secret ingredient. Save more than you think you need.",
  },
  // ── EGGS ──
  {
    name: "Scrambled Eggs on Toast",
    emoji: "🍳",
    description: "Soft, creamy eggs on toast. The ultimate 5-minute meal.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["eggs", "bread", "butter"],
    extra_ingredients: ["salt", "pepper"],
    steps: [
      "Whisk eggs with a pinch of salt.",
      "Melt butter in a pan over LOW heat. Add eggs.",
      "Stir constantly with a spatula, pulling from the edges. Remove from heat while still slightly wet.",
      "Toast bread. Pile eggs on toast and add pepper.",
    ],
    gremlin_note: "Low and slow is the law. High heat makes rubber. The gremlin has spoken.",
  },
  {
    name: "Classic Omelette",
    emoji: "🥚",
    description: "Fluffy, golden, stuffed with whatever you have. Fancy in 8 minutes.",
    time: 8,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "keto"],
    key_ingredients: ["eggs", "cheese"],
    extra_ingredients: ["butter", "salt", "pepper"],
    steps: [
      "Beat 3 eggs with salt and pepper.",
      "Melt butter in a pan over medium heat.",
      "Pour in eggs. As the edges set, use a spatula to push them toward the center.",
      "When mostly set, add cheese and any fillings on one half.",
      "Fold over and slide onto plate.",
    ],
    gremlin_note: "Omelettes are forgiving. Scramble it by accident? Call it eggs. Still delicious.",
  },
  {
    name: "Shakshuka",
    emoji: "🍅",
    description: "Eggs poached in spiced tomato sauce. Sounds fancy, stupidly easy.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "dairy-free", "halal"],
    key_ingredients: ["eggs", "tomatoes", "garlic"],
    extra_ingredients: ["onion", "olive oil", "cumin", "paprika", "salt"],
    steps: [
      "Sauté diced onion and garlic in olive oil until soft.",
      "Add crushed tomatoes, cumin, paprika, salt. Simmer 10 minutes.",
      "Make small wells in the sauce with a spoon. Crack an egg into each well.",
      "Cover and cook 5–8 minutes until whites are set but yolks are still runny.",
      "Serve from the pan with bread for dipping.",
    ],
    gremlin_note: "Eat from the pan. One less dish. The gremlin approves this choice.",
  },
  {
    name: "French Toast",
    emoji: "🍞",
    description: "Stale bread's revenge. Custardy, golden, better than anything.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["bread", "eggs", "milk"],
    extra_ingredients: ["butter", "cinnamon", "vanilla", "syrup", "powdered sugar"],
    steps: [
      "Whisk eggs, milk, cinnamon, and vanilla together in a shallow bowl.",
      "Dip bread slices in the mixture, letting them soak for 30 seconds per side.",
      "Cook in buttered pan over medium heat until golden on both sides.",
      "Serve with syrup, powdered sugar, or fruit.",
    ],
    gremlin_note: "Stale bread actually works BETTER here. It's like French toast was designed to rescue old bread.",
  },
  {
    name: "Fried Egg Sandwich",
    emoji: "🍳",
    description: "A fried egg between two pieces of bread. Underrated and elite.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["eggs", "bread"],
    extra_ingredients: ["butter", "hot sauce", "salt", "pepper"],
    steps: [
      "Fry an egg in butter over medium heat to your preferred doneness.",
      "Toast the bread.",
      "Add egg to bread with hot sauce, salt, and pepper.",
      "Eat immediately.",
    ],
    gremlin_note: "A runny yolk is non-negotiable. This is not up for debate.",
  },
  {
    name: "Egg Salad Sandwich",
    emoji: "🥚",
    description: "Creamy, tangy egg salad. Works on bread, crackers, or honestly just a spoon.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["eggs", "bread", "mayo"],
    extra_ingredients: ["mustard", "salt", "pepper", "chives"],
    steps: [
      "Hard boil eggs: cover with cold water, bring to boil, cook 10 minutes, cool in ice water.",
      "Peel and roughly chop eggs.",
      "Mix with mayo, mustard, salt, and pepper.",
      "Spread onto bread and serve.",
    ],
    gremlin_note: "Mash some yolks finer and leave some chunks. Texture is everything here.",
  },
  {
    name: "Mushroom Omelette",
    emoji: "🍄",
    description: "Earthy mushrooms folded into a fluffy egg blanket. Good at any hour.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "keto"],
    key_ingredients: ["eggs", "mushrooms"],
    extra_ingredients: ["butter", "garlic", "salt", "pepper", "thyme"],
    steps: [
      "Sauté sliced mushrooms in butter with garlic, salt, and thyme until browned.",
      "Beat eggs with salt and pepper. Make omelette in same pan.",
      "Add mushrooms to one half before folding.",
      "Slide onto plate and eat.",
    ],
    gremlin_note: "Mushrooms need HIGH heat to brown. Don't crowd the pan or they steam and go sad and grey.",
  },
  // ── RICE ──
  {
    name: "Egg Fried Rice",
    emoji: "🍳",
    description: "Leftover rice's moment to shine. Quick, savory, and oddly satisfying.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "dairy-free", "halal"],
    key_ingredients: ["rice", "eggs", "soy sauce"],
    extra_ingredients: ["garlic", "oil", "onion", "sesame oil", "green onion"],
    steps: [
      "Heat oil in a wok or large pan over high heat.",
      "Add garlic and onion, stir fry 1 minute.",
      "Push to the side, scramble eggs in the pan.",
      "Add cold rice, break up clumps. Stir fry everything together.",
      "Add soy sauce and sesame oil. Toss and serve hot.",
    ],
    gremlin_note: "COLD leftover rice only. Freshly cooked rice turns to mush. Day-old rice is the secret.",
  },
  {
    name: "Chicken Fried Rice",
    emoji: "🍚",
    description: "A full meal in one pan. Savory, filling, and made for leftovers.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["rice", "chicken", "eggs", "soy sauce"],
    extra_ingredients: ["garlic", "oil", "onion", "sesame oil"],
    steps: [
      "Cook chicken in a hot oiled pan until golden. Slice and set aside.",
      "In the same pan, fry garlic and onion for 1 minute.",
      "Scramble eggs on the side of the pan.",
      "Add cold rice, break up clumps, stir fry everything.",
      "Add chicken back, pour in soy sauce and sesame oil. Toss and serve.",
    ],
    gremlin_note: "High heat only. A hot pan is what separates fried rice from sad rice.",
  },
  {
    name: "Rice and Beans",
    emoji: "🫘",
    description: "The ultimate budget meal. Filling, nutritious, and secretly delicious.",
    time: 25,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["rice", "beans", "garlic"],
    extra_ingredients: ["onion", "oil", "cumin", "salt", "pepper"],
    steps: [
      "Cook rice according to package directions.",
      "Sauté diced onion and garlic in oil until soft.",
      "Add canned beans (drained), cumin, salt, pepper. Cook 5 minutes.",
      "Serve beans over rice.",
    ],
    gremlin_note: "Add a fried egg on top and you've got a full meal. Optional but the gremlin strongly recommends it.",
  },
  {
    name: "Chicken Rice Bowl",
    emoji: "🍚",
    description: "Juicy chicken on fluffy rice with a sauce. Simple and completely satisfying.",
    time: 25,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["rice", "chicken"],
    extra_ingredients: ["garlic", "soy sauce", "oil", "sesame oil", "ginger"],
    steps: [
      "Cook rice and keep warm.",
      "Marinate chicken in soy sauce, garlic, and ginger for 5 minutes.",
      "Cook chicken in oiled pan over medium-high heat until cooked through.",
      "Slice and serve over rice with extra sauce drizzled on top.",
    ],
    gremlin_note: "Let the chicken rest 2 minutes before slicing. All the juices stay in the meat.",
  },
  {
    name: "Stuffed Bell Peppers",
    emoji: "🫑",
    description: "Bell peppers transformed into edible bowls. Looks impressive, very achievable.",
    time: 40,
    difficulty: "Medium",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["bell peppers", "rice", "beef"],
    extra_ingredients: ["onion", "garlic", "tomatoes", "cheese", "salt", "pepper"],
    steps: [
      "Preheat oven to 190°C/375°F. Cut tops off peppers and remove seeds.",
      "Cook rice until just done. Brown beef with onion and garlic.",
      "Mix beef, rice, tomatoes, salt, and pepper together.",
      "Fill peppers with the mixture, top with cheese.",
      "Bake 30 minutes until peppers are tender.",
    ],
    gremlin_note: "Use any color pepper. The red ones are sweeter. The green ones taste like a different experience.",
  },
  // ── CHICKEN ──
  {
    name: "Honey Garlic Chicken",
    emoji: "🍯",
    description: "Sticky, sweet, garlicky chicken. Four ingredients of pure glory.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "honey", "garlic", "soy sauce"],
    extra_ingredients: ["oil", "sesame seeds", "green onion"],
    steps: [
      "Mix honey, soy sauce, and minced garlic together.",
      "Cook chicken in oiled pan over medium-high heat until golden and cooked through.",
      "Pour sauce over chicken in the pan. Let it bubble and caramelize 2 minutes.",
      "Serve over rice, topped with sesame seeds.",
    ],
    gremlin_note: "Watch the honey — it burns fast. High heat, then pull the pan. Sticky golden perfection.",
  },
  {
    name: "Chicken Stir Fry",
    emoji: "🥢",
    description: "Chicken and vegetables in a savory sauce. Weeknight hero.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chicken", "vegetables", "soy sauce", "garlic"],
    extra_ingredients: ["oil", "sesame oil", "cornstarch", "ginger"],
    steps: [
      "Slice chicken thinly and toss with a bit of soy sauce and cornstarch.",
      "Stir fry chicken in a very hot oiled pan until cooked. Remove.",
      "Stir fry vegetables in the same pan until just tender.",
      "Add chicken back, pour in soy sauce, garlic, ginger, and sesame oil.",
      "Toss everything together. Serve with rice.",
    ],
    gremlin_note: "Thin chicken slices cook in 3 minutes. Don't overcook it or it gets chewy and sad.",
  },
  {
    name: "Butter Chicken",
    emoji: "🍛",
    description: "Creamy, spiced tomato sauce hugging tender chicken. Restaurant-tier at home.",
    time: 35,
    difficulty: "Medium",
    dietary: ["gluten-free", "halal"],
    key_ingredients: ["chicken", "tomatoes", "cream", "garlic"],
    extra_ingredients: ["butter", "onion", "garam masala", "cumin", "ginger", "salt"],
    steps: [
      "Cook diced chicken in butter until browned. Remove.",
      "Sauté onion, garlic, ginger in same pan. Add spices and cook 1 minute.",
      "Add crushed tomatoes, simmer 10 minutes.",
      "Blend the sauce until smooth (optional but worth it).",
      "Add cream and chicken. Simmer 10 more minutes. Serve with rice or bread.",
    ],
    gremlin_note: "Blending the sauce is the move. Silky smooth sauce = completely different dish.",
  },
  {
    name: "Chicken Noodle Soup",
    emoji: "🍜",
    description: "The fix for everything. Warm, soothing, and tastes like someone cares about you.",
    time: 30,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken", "pasta", "carrot", "onion"],
    extra_ingredients: ["celery", "garlic", "chicken stock", "salt", "pepper", "parsley"],
    steps: [
      "Simmer diced chicken in stock or water with onion, garlic, carrot, and celery.",
      "Cook until chicken is tender, about 15 minutes. Remove chicken and shred.",
      "Add pasta to the broth and cook until done.",
      "Return chicken to pot, season with salt, pepper, and parsley.",
    ],
    gremlin_note: "Bone-in chicken makes better broth but takes longer. Use what you have — it'll still work.",
  },
  {
    name: "Chicken Tacos",
    emoji: "🌮",
    description: "Spiced chicken in warm tortillas with whatever toppings you have.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["chicken", "tortillas"],
    extra_ingredients: ["cumin", "paprika", "garlic powder", "salt", "lime", "salsa", "avocado"],
    steps: [
      "Season chicken with cumin, paprika, garlic powder, salt.",
      "Cook in oiled pan over medium-high heat until charred and cooked through.",
      "Slice into strips.",
      "Warm tortillas in a dry pan or directly on the flame.",
      "Load up tortillas with chicken and your toppings.",
    ],
    gremlin_note: "Char your tortillas directly on the burner for 10 seconds per side. Life-changing.",
  },
  {
    name: "Chicken Quesadilla",
    emoji: "🧀",
    description: "Melty cheese and chicken pressed between crispy tortillas. Perfect in every way.",
    time: 15,
    difficulty: "Easy",
    dietary: ["halal"],
    key_ingredients: ["chicken", "tortillas", "cheese"],
    extra_ingredients: ["oil", "salsa", "sour cream", "paprika"],
    steps: [
      "Cook and slice chicken. Season with salt, pepper, and paprika.",
      "Place a tortilla in a pan, cover half with cheese and chicken.",
      "Fold tortilla in half, press down gently.",
      "Cook 2–3 minutes per side until golden and crispy.",
      "Cut into wedges and serve with salsa.",
    ],
    gremlin_note: "Medium heat only. Too hot and the outside burns before the cheese melts.",
  },
  {
    name: "Grilled Chicken Salad",
    emoji: "🥗",
    description: "Charred chicken on fresh greens. Light but filling. Feels virtuous.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["chicken", "lettuce", "tomatoes"],
    extra_ingredients: ["olive oil", "lemon", "garlic", "salt", "pepper", "cucumber"],
    steps: [
      "Season chicken with olive oil, garlic, salt, and pepper.",
      "Grill or cook in a hot pan until charred and cooked through.",
      "Let chicken rest 2 minutes, then slice.",
      "Combine lettuce, tomatoes, and cucumber.",
      "Top with chicken and drizzle with olive oil and lemon.",
    ],
    gremlin_note: "Rest the chicken before cutting. Those 2 minutes are not optional.",
  },
  {
    name: "Crispy Chicken Sandwich",
    emoji: "🍗",
    description: "Golden crispy chicken on a soft bun. Better than most fast food.",
    time: 25,
    difficulty: "Medium",
    dietary: ["halal"],
    key_ingredients: ["chicken", "bread"],
    extra_ingredients: ["flour", "egg", "breadcrumbs", "oil", "mayo", "lettuce", "pickles"],
    steps: [
      "Flatten chicken breast to even thickness.",
      "Dip in flour, then beaten egg, then breadcrumbs.",
      "Fry in oil over medium-high heat, 4–5 minutes per side until golden.",
      "Spread mayo on bread, add lettuce, pickles, and the chicken.",
    ],
    gremlin_note: "Press the breadcrumbs firmly onto the chicken. They need to COMMIT.",
  },
  // ── BEEF ──
  {
    name: "Beef Tacos",
    emoji: "🌮",
    description: "Seasoned ground beef in warm tortillas. A crowd-pleaser that takes 15 minutes.",
    time: 15,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["beef", "tortillas", "onion"],
    extra_ingredients: ["garlic", "cumin", "paprika", "salt", "salsa", "lime"],
    steps: [
      "Brown ground beef in a pan, drain excess fat.",
      "Add diced onion, garlic, cumin, paprika, and salt.",
      "Cook until onion is soft and beef is fragrant.",
      "Serve in warm tortillas with your toppings.",
    ],
    gremlin_note: "Toast the tortillas. Cold tortillas are a crime.",
  },
  {
    name: "Beef Burgers",
    emoji: "🍔",
    description: "Smashed, seared, and juicy. The burger you actually want.",
    time: 20,
    difficulty: "Easy",
    dietary: ["halal"],
    key_ingredients: ["beef", "bread"],
    extra_ingredients: ["salt", "pepper", "cheese", "lettuce", "tomato", "mayo", "ketchup"],
    steps: [
      "Shape ground beef into loose balls. Season generously with salt and pepper.",
      "Heat a heavy pan until very hot. Place beef balls and smash flat with a spatula.",
      "Cook 2–3 minutes without touching. Flip once.",
      "Add cheese in last 30 seconds to melt.",
      "Assemble on toasted bun with your toppings.",
    ],
    gremlin_note: "Don't press after the initial smash. Pressing squeezes the juice out. Resist the urge.",
  },
  {
    name: "Beef Chili",
    emoji: "🌶️",
    description: "A big bowl of deep, spiced beef and beans. Gets better the longer it sits.",
    time: 45,
    difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["beef", "beans", "tomatoes"],
    extra_ingredients: ["onion", "garlic", "cumin", "chili powder", "salt"],
    steps: [
      "Brown beef in a large pot. Drain excess fat.",
      "Add diced onion and garlic, cook until soft.",
      "Add cumin, chili powder, salt. Stir 1 minute.",
      "Add crushed tomatoes and beans. Simmer 30 minutes.",
      "Serve with sour cream, cheese, or cornbread.",
    ],
    gremlin_note: "It tastes 10x better the next day. Make extra. Future you will be so relieved.",
  },
  {
    name: "Beef Stir Fry",
    emoji: "🥩",
    description: "Thin sliced beef and vegetables in a savory sauce. 15 minutes of pure win.",
    time: 15,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "halal"],
    key_ingredients: ["beef", "vegetables", "soy sauce", "garlic"],
    extra_ingredients: ["oil", "sesame oil", "cornstarch", "ginger", "oyster sauce"],
    steps: [
      "Slice beef very thin against the grain. Toss with cornstarch and soy sauce.",
      "Stir fry beef in very hot oiled wok until browned. Remove.",
      "Stir fry vegetables in the same pan.",
      "Add beef back, pour in soy sauce, garlic, ginger mix.",
      "Toss, finish with sesame oil, serve over rice.",
    ],
    gremlin_note: "Thin slices cook in seconds. Thick slices become shoe leather. Respect the thin slice.",
  },
  {
    name: "Meatballs in Tomato Sauce",
    emoji: "🍝",
    description: "Tender meatballs swimming in rich tomato sauce. Serve over pasta or with bread.",
    time: 35,
    difficulty: "Medium",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["beef", "tomatoes", "garlic"],
    extra_ingredients: ["breadcrumbs", "egg", "onion", "olive oil", "parsley", "salt", "pepper"],
    steps: [
      "Mix ground beef with breadcrumbs, egg, garlic, parsley, salt, and pepper. Form into balls.",
      "Brown meatballs in oiled pan on all sides. Remove.",
      "Sauté garlic and onion in same pan. Add crushed tomatoes. Simmer 5 minutes.",
      "Add meatballs back to sauce. Simmer 20 minutes until cooked through.",
      "Serve over pasta or with bread.",
    ],
    gremlin_note: "Don't overwork the meat when mixing — gentle hands make tender meatballs.",
  },
  // ── FISH / SEAFOOD ──
  {
    name: "Tuna Salad",
    emoji: "🐟",
    description: "Creamy, crunchy tuna salad. On bread, on crackers, on a fork. No judgement.",
    time: 5,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["tuna", "mayo"],
    extra_ingredients: ["celery", "onion", "mustard", "lemon", "salt", "pepper"],
    steps: [
      "Drain canned tuna and flake into a bowl.",
      "Mix with mayo, diced celery, onion, mustard, and lemon juice.",
      "Season with salt and pepper.",
      "Eat on bread, crackers, or straight from the bowl.",
    ],
    gremlin_note: "Let it sit 5 minutes after mixing. The flavors need a moment to meet each other.",
  },
  {
    name: "Garlic Butter Shrimp",
    emoji: "🍤",
    description: "Juicy shrimp in garlicky butter. Ready in 10 minutes and tastes expensive.",
    time: 10,
    difficulty: "Easy",
    dietary: ["gluten-free", "keto", "halal"],
    key_ingredients: ["shrimp", "garlic", "butter"],
    extra_ingredients: ["lemon", "parsley", "salt", "pepper", "chili flakes"],
    steps: [
      "Pat shrimp dry, season with salt, pepper, and chili flakes.",
      "Melt butter in a hot pan. Add garlic, cook 30 seconds.",
      "Add shrimp in a single layer. Cook 1–2 minutes per side until pink.",
      "Squeeze lemon over, sprinkle parsley. Serve immediately.",
    ],
    gremlin_note: "Shrimp overcook in seconds. Pink = done. Grey-white = done. Any longer = rubber.",
  },
  {
    name: "Baked Salmon",
    emoji: "🐟",
    description: "Flaky, perfectly cooked salmon with minimal effort. Oven does the work.",
    time: 20,
    difficulty: "Easy",
    dietary: ["dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["salmon", "lemon", "garlic"],
    extra_ingredients: ["olive oil", "salt", "pepper", "dill", "honey"],
    steps: [
      "Preheat oven to 200°C/400°F.",
      "Place salmon on a lined baking sheet. Drizzle with olive oil.",
      "Season with salt, pepper, garlic, and lemon slices on top.",
      "Bake 12–15 minutes until it flakes easily with a fork.",
    ],
    gremlin_note: "When it flakes with a fork, it's done. Don't wait for it to look dried out.",
  },
  {
    name: "Tuna Melt",
    emoji: "🧀",
    description: "Tuna salad under a blanket of melted cheese on toast. Comfort food royalty.",
    time: 10,
    difficulty: "Easy",
    dietary: ["halal"],
    key_ingredients: ["tuna", "bread", "cheese"],
    extra_ingredients: ["mayo", "onion", "mustard", "butter"],
    steps: [
      "Mix drained tuna with mayo, diced onion, and mustard.",
      "Spread onto bread slices. Top with cheese.",
      "Broil in oven or toast in a covered pan until cheese is melted and bubbly.",
      "Eat hot.",
    ],
    gremlin_note: "The cheese must be fully melted. Partially melted cheese is a tragedy.",
  },
  // ── VEGETARIAN / VEGAN ──
  {
    name: "Lentil Soup",
    emoji: "🍲",
    description: "Hearty, warming lentil soup. Filling, healthy, and impossible to mess up.",
    time: 30,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["lentils", "tomatoes", "onion"],
    extra_ingredients: ["garlic", "cumin", "paprika", "olive oil", "salt", "lemon"],
    steps: [
      "Sauté diced onion and garlic in olive oil until soft.",
      "Add cumin, paprika. Stir 1 minute.",
      "Add lentils, crushed tomatoes, and 4 cups water or stock.",
      "Simmer 25 minutes until lentils are tender.",
      "Squeeze lemon in, season with salt. Blend partially for a thicker texture.",
    ],
    gremlin_note: "Red lentils dissolve into the soup. Green lentils hold their shape. Both are correct. Pick your texture.",
  },
  {
    name: "Chickpea Curry",
    emoji: "🍛",
    description: "A rich, fragrant curry from canned chickpeas. 20 minutes to something special.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["chickpeas", "tomatoes", "garlic"],
    extra_ingredients: ["onion", "oil", "garam masala", "cumin", "coriander", "ginger", "salt"],
    steps: [
      "Sauté onion, garlic, and ginger in oil until soft.",
      "Add cumin, coriander, garam masala. Cook 1 minute until fragrant.",
      "Add crushed tomatoes, cook 5 minutes.",
      "Add drained chickpeas. Simmer 10 minutes.",
      "Serve over rice with a squeeze of lemon.",
    ],
    gremlin_note: "Toast the spices until they smell amazing before adding anything wet. That's where the flavor lives.",
  },
  {
    name: "Black Bean Tacos",
    emoji: "🫘",
    description: "Spiced black beans in warm tortillas. Accidentally vegan, accidentally amazing.",
    time: 15,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["black beans", "tortillas"],
    extra_ingredients: ["garlic", "cumin", "lime", "salsa", "avocado", "salt"],
    steps: [
      "Sauté garlic in oil, add drained black beans and cumin.",
      "Mash beans lightly with the back of a spoon. Season with salt.",
      "Warm tortillas in a dry pan.",
      "Fill tortillas with beans and your toppings.",
    ],
    gremlin_note: "Mash only HALF the beans. Half smooth, half chunky. This is the way.",
  },
  {
    name: "Veggie Stir Fry",
    emoji: "🥦",
    description: "Whatever vegetables you have, high heat, soy sauce. Done. Great.",
    time: 15,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["vegetables", "garlic", "soy sauce"],
    extra_ingredients: ["oil", "sesame oil", "ginger", "chili flakes"],
    steps: [
      "Cut vegetables into similar-sized pieces.",
      "Heat oil in a wok or large pan until smoking.",
      "Add hard vegetables first (carrots, broccoli), then soft ones (peppers, zucchini).",
      "Add garlic and ginger, stir fry 1 minute.",
      "Season with soy sauce and sesame oil. Serve over rice or noodles.",
    ],
    gremlin_note: "HOT pan, FAST cooking. Veggies should be slightly charred on the edges and crisp inside.",
  },
  {
    name: "Tomato Soup",
    emoji: "🍅",
    description: "Simple, smooth, deeply comforting. Best with grilled cheese on the side.",
    time: 25,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "halal"],
    key_ingredients: ["tomatoes", "garlic", "onion"],
    extra_ingredients: ["butter", "cream", "basil", "salt", "pepper", "sugar"],
    steps: [
      "Sauté onion and garlic in butter until soft.",
      "Add canned tomatoes, salt, pepper, and a pinch of sugar.",
      "Simmer 15 minutes.",
      "Blend until smooth.",
      "Stir in cream, taste, and adjust seasoning.",
    ],
    gremlin_note: "The pinch of sugar is not optional. It balances the acidity. Trust the process.",
  },
  {
    name: "Caprese Salad",
    emoji: "🍅",
    description: "Tomatoes, mozzarella, basil, olive oil. No cooking. Pure summer.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "keto"],
    key_ingredients: ["tomatoes", "mozzarella", "basil"],
    extra_ingredients: ["olive oil", "salt", "pepper", "balsamic glaze"],
    steps: [
      "Slice tomatoes and mozzarella into equal rounds.",
      "Alternate slices on a plate.",
      "Tuck basil leaves between them.",
      "Drizzle with olive oil, season with salt and pepper.",
      "Add balsamic glaze if you have it.",
    ],
    gremlin_note: "Salt the tomatoes. Salt the mozzarella too. Season everything.",
  },
  {
    name: "Greek Salad",
    emoji: "🫒",
    description: "Crisp vegetables and salty feta in a tangy dressing. No cooking required.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "keto", "halal"],
    key_ingredients: ["tomatoes", "cucumber", "feta"],
    extra_ingredients: ["olives", "red onion", "olive oil", "oregano", "salt", "lemon"],
    steps: [
      "Dice tomatoes and cucumber into chunky pieces.",
      "Add sliced red onion and olives.",
      "Crumble feta over the top.",
      "Dress with olive oil, lemon juice, oregano, and salt.",
      "Toss gently and serve.",
    ],
    gremlin_note: "Chunky pieces only. Greek salad should be rustic and bold, not dainty.",
  },
  {
    name: "Avocado Toast",
    emoji: "🥑",
    description: "The millennial icon. Creamy avocado on toast. Endlessly customizable.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["avocado", "bread"],
    extra_ingredients: ["lemon", "salt", "pepper", "chili flakes", "eggs", "tomatoes"],
    steps: [
      "Toast the bread until golden and crispy.",
      "Mash avocado with lemon juice, salt, and pepper.",
      "Spread onto toast.",
      "Top with whatever you have — poached egg, tomatoes, chili flakes.",
    ],
    gremlin_note: "The avocado must be ripe. A firm avocado is not ready. No amount of force will fix it.",
  },
  {
    name: "Grilled Cheese Sandwich",
    emoji: "🧀",
    description: "Butter, bread, cheese, heat. Four elements. Perfect sandwich.",
    time: 8,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["bread", "cheese", "butter"],
    extra_ingredients: ["garlic powder", "hot sauce"],
    steps: [
      "Butter the outside of both bread slices.",
      "Add cheese between the slices.",
      "Cook in a pan over MEDIUM-LOW heat. Patience is required.",
      "Flip when golden brown. Cook other side until cheese is fully melted.",
      "Cut diagonally. Non-negotiable.",
    ],
    gremlin_note: "MEDIUM-LOW heat. Rushing this on high heat gives you burnt bread and cold cheese. Ask me how I know.",
  },
  // ── SOUPS ──
  {
    name: "Vegetable Soup",
    emoji: "🥣",
    description: "A pot of whatever vegetables you have, turned into something comforting.",
    time: 30,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["vegetables", "onion", "garlic"],
    extra_ingredients: ["olive oil", "stock", "salt", "pepper", "thyme", "bay leaf"],
    steps: [
      "Sauté onion and garlic in olive oil until soft.",
      "Add diced vegetables — harder ones first (carrot, potato), then softer (zucchini, greens).",
      "Pour in stock or water to cover. Add thyme and bay leaf.",
      "Simmer 20 minutes until everything is tender.",
      "Season with salt and pepper.",
    ],
    gremlin_note: "This soup is designed for the vegetables that are about to go bad. You're saving them. Noble work.",
  },
  {
    name: "Potato Soup",
    emoji: "🥔",
    description: "Thick, creamy potato soup. The definition of cozy.",
    time: 30,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["potatoes", "onion", "milk"],
    extra_ingredients: ["butter", "garlic", "chicken or veg stock", "salt", "pepper", "cheese", "chives"],
    steps: [
      "Dice potatoes and onion. Sauté onion in butter until soft.",
      "Add potatoes and enough stock to cover. Boil until potatoes are tender, 15 minutes.",
      "Mash some potatoes in the pot for a chunky-creamy texture.",
      "Stir in milk, season with salt and pepper.",
      "Serve topped with cheese and chives.",
    ],
    gremlin_note: "Mash only HALF the potatoes in the pot. Half smooth, half chunky. Perfect texture.",
  },
  {
    name: "Minestrone",
    emoji: "🍅",
    description: "The Italian everything soup. Vegetables, beans, pasta in a herby broth.",
    time: 35,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["vegetables", "beans", "tomatoes", "pasta"],
    extra_ingredients: ["garlic", "onion", "olive oil", "stock", "basil", "oregano", "salt"],
    steps: [
      "Sauté onion and garlic in olive oil.",
      "Add diced vegetables and cook 5 minutes.",
      "Add crushed tomatoes, beans, stock, and dried herbs.",
      "Simmer 15 minutes. Add pasta and cook until done.",
      "Season and serve with a drizzle of olive oil.",
    ],
    gremlin_note: "Add the pasta last or it absorbs all the broth overnight. Unless you like pasta porridge.",
  },
  {
    name: "Quick Ramen",
    emoji: "🍜",
    description: "Instant ramen upgraded with real toppings. 10 minutes to a serious bowl.",
    time: 10,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["noodles", "eggs", "soy sauce"],
    extra_ingredients: ["garlic", "ginger", "sesame oil", "chili oil", "green onion", "stock"],
    steps: [
      "Simmer stock or water with garlic, ginger, and soy sauce for 5 minutes.",
      "Cook noodles according to package. Soft boil an egg separately.",
      "Pour hot broth into bowl, add noodles.",
      "Halve the soft-boiled egg and place on top.",
      "Finish with sesame oil, chili oil, and green onion.",
    ],
    gremlin_note: "The soft-boiled egg is the crown jewel. 6 minutes in boiling water, then ice bath. Trust it.",
  },
  // ── BREAKFAST / SNACKS ──
  {
    name: "Pancakes",
    emoji: "🥞",
    description: "Fluffy, golden pancakes from scratch. Better than a mix.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["flour", "eggs", "milk"],
    extra_ingredients: ["butter", "baking powder", "sugar", "salt", "vanilla", "syrup"],
    steps: [
      "Mix flour, baking powder, sugar, and salt together.",
      "Whisk in egg, milk, melted butter, and vanilla.",
      "Let batter rest 5 minutes. It should be slightly lumpy.",
      "Cook on a buttered pan over medium heat. Flip when bubbles form on the surface.",
      "Serve with butter and syrup.",
    ],
    gremlin_note: "Lumpy batter = fluffier pancakes. Don't overmix. Leave the lumps alone.",
  },
  {
    name: "Banana Pancakes",
    emoji: "🍌",
    description: "Two ingredients. Banana and eggs. That's it. Seriously.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "dairy-free", "halal"],
    key_ingredients: ["banana", "eggs"],
    extra_ingredients: ["cinnamon", "vanilla", "butter", "honey"],
    steps: [
      "Mash 1 ripe banana in a bowl until smooth.",
      "Mix in 2 eggs and a pinch of cinnamon.",
      "Cook small pancakes in a buttered pan over medium-low heat.",
      "Flip carefully when edges are set (they're fragile!).",
      "Serve with honey or fruit.",
    ],
    gremlin_note: "These are fragile — small and low heat only. They're not regular pancakes. They're magic.",
  },
  {
    name: "Banana Oatmeal",
    emoji: "🍌",
    description: "Creamy oats with sweet banana. Breakfast that actually keeps you full.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "halal"],
    key_ingredients: ["oats", "banana", "milk"],
    extra_ingredients: ["cinnamon", "honey", "nuts", "berries"],
    steps: [
      "Cook oats in milk or water per package instructions.",
      "Slice or mash banana into the oats.",
      "Stir in cinnamon.",
      "Top with honey, nuts, or berries.",
    ],
    gremlin_note: "Mash the banana IN while cooking. It melts in and sweetens the whole thing without added sugar.",
  },
  {
    name: "Overnight Oats",
    emoji: "🥣",
    description: "Zero morning effort. Make at night, eat in the morning. Genius.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["oats", "milk"],
    extra_ingredients: ["yogurt", "honey", "chia seeds", "vanilla", "fruit", "nut butter"],
    steps: [
      "Mix oats, milk, yogurt, honey, and chia seeds in a jar.",
      "Stir well. The ratio is roughly 1:1 oats to liquid.",
      "Cover and refrigerate overnight (or minimum 4 hours).",
      "In the morning, top with fruit, nut butter, or whatever you like.",
    ],
    gremlin_note: "The chia seeds make it thick and creamy. Add more milk in the morning if it's too thick.",
  },
  {
    name: "Garlic Bread",
    emoji: "🧄",
    description: "Butter, garlic, bread, heat. An underrated standalone meal option.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["bread", "garlic", "butter"],
    extra_ingredients: ["parsley", "parmesan", "salt"],
    steps: [
      "Mix softened butter with minced garlic and chopped parsley.",
      "Spread generously over bread slices or a halved baguette.",
      "Wrap in foil and bake at 180°C/350°F for 10 minutes.",
      "Unwrap for last 2 minutes to crisp up.",
    ],
    gremlin_note: "More garlic butter than seems reasonable. That is the correct amount.",
  },
  {
    name: "Bruschetta",
    emoji: "🍅",
    description: "Toasted bread with garlicky fresh tomatoes. Italian perfection.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["bread", "tomatoes", "garlic", "basil"],
    extra_ingredients: ["olive oil", "salt", "pepper", "balsamic"],
    steps: [
      "Dice tomatoes, mix with minced garlic, basil, olive oil, salt, and pepper.",
      "Let sit 10 minutes so flavors merge.",
      "Toast or grill bread until crispy.",
      "Rub warm bread with a cut garlic clove.",
      "Spoon tomatoes on top. Eat immediately.",
    ],
    gremlin_note: "Let the tomato mixture sit. 10 minutes of patience turns it from good to incredible.",
  },
  {
    name: "Nachos",
    emoji: "🧀",
    description: "Chips buried under melted cheese and toppings. A beautiful disaster.",
    time: 15,
    difficulty: "Easy",
    dietary: ["vegetarian"],
    key_ingredients: ["tortilla chips", "cheese", "beans"],
    extra_ingredients: ["salsa", "sour cream", "jalapeños", "avocado", "tomatoes"],
    steps: [
      "Spread chips in a single layer on a baking sheet.",
      "Top with grated cheese and beans.",
      "Bake at 200°C/400°F for 8–10 minutes until cheese is melted and bubbly.",
      "Add cold toppings: salsa, sour cream, jalapeños, avocado.",
      "Eat immediately. Soggy nachos are a tragedy.",
    ],
    gremlin_note: "Single layer chips = every chip gets cheese. Piling chips = sad cheeseless chips at the bottom.",
  },
  {
    name: "PB&J",
    emoji: "🥜",
    description: "Peanut butter and jelly. No explanation needed. No shame either.",
    time: 3,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["bread", "peanut butter", "jam"],
    extra_ingredients: ["banana", "honey"],
    steps: [
      "Spread peanut butter on one slice of bread.",
      "Spread jam on the other slice.",
      "Press together.",
      "Eat.",
    ],
    gremlin_note: "Add banana slices inside. Completely transforms it. You can thank the gremlin later.",
  },
  {
    name: "Cheese Quesadilla",
    emoji: "🧀",
    description: "Cheese melted inside a crispy tortilla. The perfect 5-minute meal.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["tortillas", "cheese"],
    extra_ingredients: ["butter", "salsa", "sour cream"],
    steps: [
      "Place a tortilla in a dry pan over medium heat.",
      "Sprinkle cheese over half the tortilla.",
      "Fold the empty half over the cheese.",
      "Cook 2 minutes per side until crispy and cheese is melted.",
      "Cut into triangles. Dip in salsa.",
    ],
    gremlin_note: "Dry pan, no butter. Butter makes it greasy and soft. You want crispy.",
  },
  // ── MISC / ELEVATED ──
  {
    name: "Mushroom Risotto",
    emoji: "🍄",
    description: "Creamy, earthy risotto. Requires patience but rewards it completely.",
    time: 40,
    difficulty: "Medium",
    dietary: ["vegetarian"],
    key_ingredients: ["rice", "mushrooms", "parmesan", "onion"],
    extra_ingredients: ["butter", "white wine", "vegetable stock", "garlic", "salt", "pepper"],
    steps: [
      "Sauté sliced mushrooms in butter until golden. Set aside.",
      "In the same pot, cook diced onion and garlic in butter until soft.",
      "Add rice and stir to coat. Add wine if using, cook until absorbed.",
      "Add warm stock one ladle at a time, stirring constantly. Repeat until rice is creamy and al dente, about 20 minutes.",
      "Stir in mushrooms, butter, and parmesan. Season and serve immediately.",
    ],
    gremlin_note: "Warm stock only. Cold stock shocks the rice and ruins the texture. Keep that pot warm.",
  },
  {
    name: "Hummus Wraps",
    emoji: "🫓",
    description: "Hummus, veggies, and whatever else you have, wrapped up and eaten.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "halal"],
    key_ingredients: ["tortillas", "hummus", "vegetables"],
    extra_ingredients: ["cucumber", "tomatoes", "lettuce", "lemon", "olives"],
    steps: [
      "Spread a thick layer of hummus on a tortilla.",
      "Pile on sliced vegetables — cucumber, tomato, lettuce, olives.",
      "Squeeze lemon over everything.",
      "Roll tightly and eat.",
    ],
    gremlin_note: "Use way more hummus than seems right. It's the whole point. Don't be shy.",
  },
  {
    name: "Steak",
    emoji: "🥩",
    description: "A properly cooked steak needs almost nothing. Salt, heat, butter, done.",
    time: 15,
    difficulty: "Medium",
    dietary: ["dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["steak", "garlic", "butter"],
    extra_ingredients: ["salt", "pepper", "rosemary", "thyme"],
    steps: [
      "Take steak out of the fridge 20 minutes before cooking. Pat dry.",
      "Season GENEROUSLY with salt and pepper on both sides.",
      "Heat pan until very hot. Sear steak 2–3 minutes per side for medium-rare.",
      "In the last minute, add butter, garlic, and herbs. Baste the steak.",
      "REST for 5 minutes before cutting. This is mandatory.",
    ],
    gremlin_note: "The resting is not optional. Cut it early and all the juices spill out. 5 minutes. Be patient.",
  },
  {
    name: "Shakshuka with Feta",
    emoji: "🧀",
    description: "The original shakshuka's richer cousin — eggs in spiced tomato sauce with salty feta.",
    time: 20,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "halal"],
    key_ingredients: ["eggs", "tomatoes", "feta"],
    extra_ingredients: ["onion", "garlic", "olive oil", "cumin", "paprika", "salt"],
    steps: [
      "Sauté diced onion and garlic in olive oil.",
      "Add cumin, paprika, crushed tomatoes. Simmer 10 minutes.",
      "Crumble feta over the sauce.",
      "Make wells, crack eggs in. Cover and cook until whites are set.",
      "Serve straight from the pan with pita or bread.",
    ],
    gremlin_note: "Feta changes everything. It melts slightly into the sauce and gets tangy and salty. Essential.",
  },
  {
    name: "Fried Banana with Honey",
    emoji: "🍌",
    description: "Caramelized banana in butter and honey. A 5-minute dessert that impresses.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "halal"],
    key_ingredients: ["banana", "honey", "butter"],
    extra_ingredients: ["cinnamon", "vanilla ice cream"],
    steps: [
      "Slice bananas in half lengthwise.",
      "Melt butter in a pan over medium heat.",
      "Place bananas cut side down and cook 2 minutes until golden.",
      "Flip, drizzle with honey and cinnamon.",
      "Cook 1 more minute. Serve with ice cream.",
    ],
    gremlin_note: "Don't touch them until they're golden. Caramelization needs commitment.",
  },
  {
    name: "Turkey & Avocado Sandwich",
    emoji: "🥪",
    description: "Stacked sandwich with turkey, creamy avocado, and crunch. Quick and filling.",
    time: 5,
    difficulty: "Easy",
    dietary: ["dairy-free", "halal"],
    key_ingredients: ["bread", "turkey", "avocado"],
    extra_ingredients: ["lettuce", "tomato", "mayo", "mustard", "salt", "pepper"],
    steps: [
      "Toast bread if desired.",
      "Mash or slice avocado on one side.",
      "Add turkey, lettuce, and tomato.",
      "Spread mayo or mustard on the other slice.",
      "Season with salt, pepper, and assemble.",
    ],
    gremlin_note: "Press the sandwich down slightly after assembling. It holds together and tastes better. Physics.",
  },
  {
    name: "Spinach and Cheese Omelette",
    emoji: "🥬",
    description: "A protein-packed omelette stuffed with wilted spinach and melted cheese.",
    time: 8,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free", "keto"],
    key_ingredients: ["eggs", "spinach", "cheese"],
    extra_ingredients: ["butter", "garlic", "salt", "pepper"],
    steps: [
      "Wilt spinach in butter with garlic for 1 minute. Set aside.",
      "Beat eggs with salt and pepper. Pour into buttered pan.",
      "When mostly set, add spinach and cheese to one half.",
      "Fold and slide onto plate.",
    ],
    gremlin_note: "Dry the spinach before adding it or the omelette goes soggy and sad.",
  },
  {
    name: "Yogurt Parfait",
    emoji: "🍓",
    description: "Creamy yogurt layered with granola and fruit. Breakfast that looks effortful.",
    time: 5,
    difficulty: "Easy",
    dietary: ["vegetarian", "gluten-free"],
    key_ingredients: ["yogurt", "fruit"],
    extra_ingredients: ["granola", "honey", "nuts", "seeds"],
    steps: [
      "Spoon yogurt into a glass or bowl.",
      "Add a layer of granola.",
      "Add fresh or frozen fruit.",
      "Repeat layers. Drizzle with honey.",
    ],
    gremlin_note: "Frozen berries work perfectly here. They thaw in 5 minutes and taste great.",
  },
  {
    name: "Roasted Vegetables",
    emoji: "🥕",
    description: "Vegetables transformed by high heat into caramelized, crispy magic.",
    time: 30,
    difficulty: "Easy",
    dietary: ["vegan", "vegetarian", "dairy-free", "gluten-free", "keto", "halal"],
    key_ingredients: ["vegetables", "garlic"],
    extra_ingredients: ["olive oil", "salt", "pepper", "herbs", "lemon"],
    steps: [
      "Preheat oven to 220°C/425°F.",
      "Chop vegetables into similar-sized pieces.",
      "Toss with olive oil, garlic, salt, and pepper.",
      "Spread on a baking sheet in a single layer — NO overcrowding.",
      "Roast 25 minutes, flipping halfway, until golden and caramelized.",
    ],
    gremlin_note: "High heat. Single layer. Don't crowd the pan. These three rules separate good roasted veg from sad steamed veg.",
  },
  {
    name: "Bean and Cheese Burrito",
    emoji: "🌯",
    description: "Hearty beans and melted cheese wrapped in a warm tortilla. Cheap and deeply satisfying.",
    time: 10,
    difficulty: "Easy",
    dietary: ["vegetarian", "halal"],
    key_ingredients: ["tortillas", "beans", "cheese"],
    extra_ingredients: ["sour cream", "salsa", "cumin", "garlic", "rice"],
    steps: [
      "Warm beans in a pan with cumin and garlic. Mash slightly.",
      "Warm tortilla in a dry pan.",
      "Spread beans on tortilla, add cheese and any toppings.",
      "Fold sides in, then roll from the bottom into a tight burrito.",
      "Toast folded side down in pan for 1 minute to seal.",
    ],
    gremlin_note: "Seam side down in the pan. It seals the burrito and keeps everything from exploding.",
  },
];

function parseTimeLimit(timeLimit: string): number {
  if (timeLimit === "15 mins") return 15;
  if (timeLimit === "30 mins") return 30;
  if (timeLimit === "45 mins") return 45;
  if (timeLimit === "1 hour") return 60;
  return Infinity;
}

function ingredientMatch(userIngredients: string[], recipeIngredients: string[]): string[] {
  return recipeIngredients.filter((ri) =>
    userIngredients.some((ui) => {
      const a = ui.toLowerCase();
      const b = ri.toLowerCase();
      return a.includes(b) || b.includes(a);
    })
  );
}

export function resolveRecipe(recipe: Recipe, userIngredients: string[]): ResolvedRecipe {
  const matched = ingredientMatch(userIngredients, recipe.key_ingredients);
  const filteredExtras = recipe.extra_ingredients.filter(
    (ei) => !ingredientMatch(userIngredients, [ei]).length
  );
  return {
    name: recipe.name,
    emoji: recipe.emoji,
    description: recipe.description,
    time: `${recipe.time} mins`,
    difficulty: recipe.difficulty,
    matched_ingredients: matched,
    extra_ingredients: filteredExtras,
    steps: recipe.steps,
    gremlin_note: recipe.gremlin_note,
    cuisine: recipe.cuisine,
    level: recipe.level,
    servings: recipe.servings,
    calories: recipe.calories,
  };
}

export function matchRecipe(
  ingredients: string,
  dietary: string,
  timeLimit: string,
  level: string = "All",
  pool: Recipe[] = RECIPES
): ResolvedRecipe {
  const userIngredients = ingredients
    .toLowerCase()
    .split(/[,\n]+/)
    .map((s) => s.trim())
    .filter(Boolean);

  const maxTime = parseTimeLimit(timeLimit);
  const dietaryTag = dietary.toLowerCase();

  let candidates = pool.filter((r) => {
    const meetsTime = r.time <= maxTime;
    const meetsDiet = dietary === "None" || r.dietary.includes(dietaryTag);
    const meetsLevel = level === "All" || r.level === level || !r.level;
    return meetsTime && meetsDiet && meetsLevel;
  });

  if (candidates.length === 0) {
    candidates = pool.filter((r) => dietary === "None" || r.dietary.includes(dietaryTag));
  }
  if (candidates.length === 0) candidates = pool;

  const scored = candidates.map((r) => {
    const matched = ingredientMatch(userIngredients, r.key_ingredients);
    return { recipe: r, matched, score: matched.length };
  });

  scored.sort((a, b) => b.score - a.score);

  const topScore = scored[0].score;
  const topCandidates = scored.filter((s) => s.score === topScore);
  const { recipe } = topCandidates[Math.floor(Math.random() * topCandidates.length)];

  return resolveRecipe(recipe, userIngredients);
}
