export const INGREDIENT_SWAPS: Record<string, string> = {
  // Dairy
  "heavy cream": "coconut cream",
  "cream": "coconut cream",
  "butter": "olive oil",
  "milk": "oat milk or almond milk",
  "parmesan": "nutritional yeast or pecorino",
  "pecorino": "parmesan",
  "mozzarella": "provolone or fontina",
  "ricotta": "cottage cheese (blended smooth)",
  "mascarpone": "cream cheese + splash of cream",
  // Proteins
  "chicken": "tofu or chickpeas",
  "beef": "lamb or portobello mushrooms",
  "lamb": "beef or chicken",
  "veal": "chicken breast",
  "beef shank": "lamb shank",
  "lamb shoulder": "pork shoulder",
  "guanciale": "bacon or pancetta",
  "pancetta": "bacon or smoked ham",
  "prosciutto": "ham or smoked turkey",
  "anchovies": "capers + extra salt",
  "fish": "chicken breast or tofu",
  "ground beef": "ground turkey or lamb",
  // Produce
  "lemon": "lime",
  "lime": "lemon",
  "eggplant": "zucchini",
  "fresh basil": "dried basil or fresh mint",
  "fresh parsley": "dried parsley or cilantro",
  "fresh cilantro": "fresh parsley",
  "fresh coriander": "fresh parsley",
  "sage": "fresh thyme",
  "rosemary": "thyme or oregano",
  "kale": "spinach or chard",
  "roasted peppers": "canned roasted peppers",
  "cannellini beans": "white beans or butter beans",
  "ladyfingers": "sponge cake or shortbread cookies",
  // Pantry
  "white wine": "chicken broth + splash of white wine vinegar",
  "red wine": "beef broth + splash of red wine vinegar",
  "marsala": "dry sherry or madeira",
  "saffron": "turmeric + pinch of paprika",
  "breadcrumbs": "crushed crackers or panko",
  "cornstarch": "arrowroot powder or plain flour",
  "pine nuts": "walnuts or slivered almonds",
  "almonds": "cashews or walnuts",
  "tahini": "almond butter + sesame oil",
  "preserved lemon": "lemon zest + pinch of extra salt",
  "harissa": "chili paste + pinch of cumin",
  "ras el hanout": "equal parts cumin, coriander, cinnamon + pinch of ginger",
  "cinnamon stick": "¼ tsp ground cinnamon",
  "olives": "capers",
  "capers": "chopped olives",
  "prunes": "raisins or dried apricots",
  "dried fava beans": "split peas or yellow lentils",
  "fenugreek": "celery seeds + pinch of mustard",
  "couscous": "bulgur wheat or orzo",
  "vermicelli": "thin rice noodles or angel hair pasta",
  "pastry sheets": "phyllo dough",
};
