export const INGREDIENT_SWAPS: Record<string, string> = {
  // Dairy
  "heavy cream": "coconut cream",
  "cream": "coconut cream",
  "butter": "olive oil",
  "milk": "oat milk or almond milk",
  "parmesan": "nutritional yeast or pecorino",
  "pecorino": "parmesan",
  "mozzarella": "provolone or fontina",
  "ricotta": "cottage cheese (blended smooth)",
  "mascarpone": "cream cheese + splash of cream",
  // Proteins
  "chicken": "tofu or chickpeas",
  "beef": "lamb or portobello mushrooms",
  "lamb": "beef or chicken",
  "veal": "chicken breast",
  "beef shank": "lamb shank",
  "lamb shoulder": "pork shoulder",
  "guanciale": "bacon or pancetta",
  "pancetta": "bacon or smoked ham",
  "prosciutto": "ham or smoked turkey",
  "anchovies": "capers + extra salt",
  "fish": "chicken breast or tofu",
  "ground beef": "ground turkey or lamb",
  // Produce
  "lemon": "lime",
  "lime": "lemon",
  "eggplant": "zucchini",
  "fresh basil": "dried basil or fresh mint",
  "fresh parsley": "dried parsley or cilantro",
  "fresh cilantro": "fresh parsley",
  "fresh coriander": "fresh parsley",
  "sage": "fresh thyme",
  "rosemary": "thyme or oregano",
  "kale": "spinach or chard",
  "roasted peppers": "canned roasted peppers",
  "cannellini beans": "white beans or butter beans",
  "ladyfingers": "sponge cake or shortbread cookies",
  // Pantry
  "white wine": "chicken broth + splash of white wine vinegar",
  "red wine": "beef broth + splash of red wine vinegar",
  "marsala": "dry sherry or madeira",
  "saffron": "turmeric + pinch of paprika",
  "breadcrumbs": "crushed crackers or panko",
  "cornstarch": "arrowroot powder or plain flour",
  "pine nuts": "walnuts or slivered almonds",
  "almonds": "cashews or walnuts",
  "tahini": "almond butter + sesame oil",
  "preserved lemon": "lemon zest + pinch of extra salt",
  "harissa": "chili paste + pinch of cumin",
  "ras el hanout": "equal parts cumin, coriander, cinnamon + pinch of ginger",
  "cinnamon stick": "¼ tsp ground cinnamon",
  "olives": "capers",
  "capers": "chopped olives",
  "prunes": "raisins or dried apricots",
  "dried fava beans": "split peas or yellow lentils",
  "fenugreek": "celery seeds + pinch of mustard",
  "couscous": "bulgur wheat or orzo",
  "vermicelli": "thin rice noodles or angel hair pasta",
  "pastry sheets": "phyllo dough",
  // Japanese
  "miso paste": "soy sauce + a pinch of sesame oil",
  "dashi": "light chicken or vegetable broth",
  "mirin": "dry sherry + 1 tsp sugar",
  "sake": "dry white wine or mirin",
  "panko": "regular breadcrumbs (lightly toasted)",
  "tofu": "chicken breast or halloumi",
  "nori": "dried seaweed snacks",
  "soy sauce": "tamari (gluten-free) or coconut aminos",
  "sesame oil": "toasted sunflower oil + pinch of sesame seeds",
  "rice vinegar": "apple cider vinegar (use a little less)",
  "bonito flakes": "small pinch of smoked paprika in broth",
  // Thai
  "lemongrass": "lemon zest + fresh ginger",
  "galangal": "fresh ginger (use slightly less)",
  "kaffir lime leaves": "lime zest",
  "fish sauce": "soy sauce + squeeze of lime",
  "palm sugar": "brown sugar or honey",
  "thai basil": "regular basil + a few mint leaves",
  "thai chili": "serrano or jalapeño",
  "coconut milk": "heavy cream + pinch of coconut extract",
  "shrimp paste": "fish sauce + extra anchovies",
  // Mexican
  "masa harina": "fine cornmeal (not polenta)",
  "achiote": "paprika + pinch of turmeric and oregano",
  "chipotle": "smoked paprika + cayenne",
  "poblano": "green bell pepper + pinch of cayenne",
  "ancho chili": "guajillo or dried mulato chili",
  "cotija cheese": "feta cheese",
  "queso fresco": "mild feta or ricotta salata",
  "tomatillos": "green tomatoes + squeeze of lime",
  // Indian
  "garam masala": "equal parts cumin, coriander, cardamom, cinnamon",
  "paneer": "firm tofu or halloumi",
  "ghee": "clarified butter or regular butter",
  "curry leaves": "bay leaves (not the same, but functional)",
  "mustard seeds": "celery seeds",
  "cardamom": "a mix of cinnamon and a pinch of clove",
  "tamarind": "lime juice + pinch of brown sugar",
  "dried red chilies": "cayenne + paprika",
  "turmeric": "mild curry powder",
};
